Bus::create('line' => 101, 'itinerary' => 'AGLOMERADO SANTA LUCIA');
Bus::create('line' => 102, 'itinerary' => 'NOSSA SENHORA DE FATIMA/HOSPITAL EVANGELICO');
Bus::create('line' => 103, 'itinerary' => 'VILA CAFEZAL/RUA POUSO ALTO');
Bus::create('line' => 1030, 'itinerary' => 'AVENIDA');
Bus::create('line' => 104, 'itinerary' => 'ESTACAO LAGOINHA / AVENIDA');
Bus::create('line' => 105, 'itinerary' => 'ESTACAO CENTRAL / LOURDES');
Bus::create('line' => 107, 'itinerary' => 'VILA MARCOLA / RUA DO OURO');
Bus::create('line' => 1145, 'itinerary' => 'BAIRRO DAS INDUSTRIAS');
Bus::create('line' => 1170, 'itinerary' => 'SANTA LUCIA/MANGABEIRAS');
Bus::create('line' => 1207A, 'itinerary' => 'BETANIA/SANTA MONICA');
Bus::create('line' => 1207B, 'itinerary' => 'CONJUNTO BETANIA/SANTA MONICA');
Bus::create('line' => 1207C, 'itinerary' => 'BAIRRO DAS INDUSTRIAS - 4A SECAO/SANTA MONICA');
Bus::create('line' => 1404A, 'itinerary' => 'PALMEIRAS / ALIPIO DE MELO');
Bus::create('line' => 1404B, 'itinerary' => 'ESTRELA DO ORIENTE / JARDIM INCONFIDENCIA');
Bus::create('line' => 1404C, 'itinerary' => 'PALMEIRAS / SAO SALVADOR');
Bus::create('line' => 1502, 'itinerary' => 'VISTA ALEGRE / GUARANI');
Bus::create('line' => 1505, 'itinerary' => 'ALTO DOS PINHEIROS/TUPI');
Bus::create('line' => 1505R, 'itinerary' => 'CONJUNTO FELICIDADE / CENTRO');
Bus::create('line' => 1509, 'itinerary' => 'CALIFORNIA/TUPI');
Bus::create('line' => 1510, 'itinerary' => 'MADRE GERTRUDES/PROVIDENCIA');
Bus::create('line' => 2004, 'itinerary' => 'BANDEIRANTES/PILAR VIA OLHOS D AGUA');
Bus::create('line' => 201, 'itinerary' => 'MORRO DAS PEDRAS');
Bus::create('line' => 202, 'itinerary' => 'ESTACAO VILA OESTE');
Bus::create('line' => 203, 'itinerary' => 'MORRO DAS PEDRAS/VENTOSA');
Bus::create('line' => 204, 'itinerary' => 'ESTACAO VILA OESTE / NOVA GAMELEIRA');
Bus::create('line' => 205, 'itinerary' => 'METRO CALAFATE/BURITIS');
Bus::create('line' => 206, 'itinerary' => 'CIRCULAR OESTE');
Bus::create('line' => 2101, 'itinerary' => 'GRAJAU/SION');
Bus::create('line' => 2102, 'itinerary' => 'GAMELEIRA / SERRA');
Bus::create('line' => 2103, 'itinerary' => 'PRADO/ANCHIETA');
Bus::create('line' => 2104, 'itinerary' => 'NOVA GAMELEIRA/BH SHOPPING');
Bus::create('line' => 2150, 'itinerary' => 'GRAJAU/SION VIA CONTORNO');
Bus::create('line' => 2151, 'itinerary' => 'VISTA ALEGRE/SERRA');
Bus::create('line' => 2152, 'itinerary' => 'SALGADO FILHO/CRUZEIRO');
Bus::create('line' => 2207, 'itinerary' => 'SERRA VERDE');
Bus::create('line' => 2208B, 'itinerary' => 'JARDIM EUROPA');
Bus::create('line' => 2210A, 'itinerary' => 'RIO BRANCO');
Bus::create('line' => 2210B, 'itinerary' => 'JARDIM LEBLON VIA RIO BRANCO');
Bus::create('line' => 2210C, 'itinerary' => 'PIRATININGA VIA RIO BRANCO');
Bus::create('line' => 2211A, 'itinerary' => 'CAMPO ALEGRE');
Bus::create('line' => 2211B, 'itinerary' => 'PLANALTO');
Bus::create('line' => 2212A, 'itinerary' => 'JARDIM ATLANTICO');
Bus::create('line' => 2212B, 'itinerary' => 'JARDIM LEBLON');
Bus::create('line' => 2212C, 'itinerary' => 'COPACABANA VIA MONTE CARMELO');
Bus::create('line' => 2213, 'itinerary' => 'TREVO VIA GARCAS');
Bus::create('line' => 2214, 'itinerary' => 'FLORAMAR');
Bus::create('line' => 2215A, 'itinerary' => 'CEU AZUL A');
Bus::create('line' => 2215B, 'itinerary' => 'CEU AZUL B');
Bus::create('line' => 2215C, 'itinerary' => 'CEU AZUL C');
Bus::create('line' => 2215D, 'itinerary' => 'CEU AZUL D');
Bus::create('line' => 2216, 'itinerary' => 'SANTA BRANCA');
Bus::create('line' => 2224A, 'itinerary' => 'JARDIM DOS COMERCIARIOS A');
Bus::create('line' => 2224C, 'itinerary' => 'JARDIM DOS COMERCIARIOS C');
Bus::create('line' => 2234A, 'itinerary' => 'JAQUELINE A');
Bus::create('line' => 2234B, 'itinerary' => 'JAQUELINE B');
Bus::create('line' => 2256A, 'itinerary' => 'SAO JOAO BATISTA A');
Bus::create('line' => 2402A, 'itinerary' => 'SAO BERNARDO/NOSSA SENHORA DA GLORIA A');
Bus::create('line' => 30, 'itinerary' => 'ESTACAO DIAMANTE/CENTRO');
Bus::create('line' => 301, 'itinerary' => 'EST.DIAMANTE/NOVO STA.CECILIA V. BRASIL INDUSTRIAL');
Bus::create('line' => 302, 'itinerary' => 'ESTACAO DIAMANTE / VILA PINHO');
Bus::create('line' => 3029, 'itinerary' => 'REGINA / CENTRO');
Bus::create('line' => 303, 'itinerary' => 'ESTACAO DIAMANTE / SANTA CECILIA VIA CASTANHEIRAS');
Bus::create('line' => 304, 'itinerary' => 'ESTACAO DIAMANTE / JATOBA IV');
Bus::create('line' => 305, 'itinerary' => 'ESTACAO DIAMANTE / MANGUEIRAS');
Bus::create('line' => 3050, 'itinerary' => 'ESTACAO DIAMANTE/HOSPITAIS VIA BH SHOPPING');
Bus::create('line' => 3051, 'itinerary' => 'FLAVIO MARQUES LISBOA / SAVASSI VIA N.S.CARMO');
Bus::create('line' => 3052, 'itinerary' => 'ESTACAO DIAMANTE/BH SHOPPING-VIA HAVAI');
Bus::create('line' => 3053, 'itinerary' => 'ESTACAO BARREIRO/B.PRETO');
Bus::create('line' => 3054, 'itinerary' => 'MILIONARIOS/CENTRO');
Bus::create('line' => 3055, 'itinerary' => 'ESTACAO BARREIRO/SAVASSI VIA BHSHOPPING');
Bus::create('line' => 308, 'itinerary' => 'ESTACAO BARREIRO / TIROL');
Bus::create('line' => 309, 'itinerary' => 'ESTACAO DIAMANTE / BAIRRO PETROPOLIS');
Bus::create('line' => 310, 'itinerary' => 'ESTACAO DIAMANTE / 3 E 4 SECAO');
Bus::create('line' => 311, 'itinerary' => 'ESTACAO DIAMANTE / INDEPENDENCIA');
Bus::create('line' => 313, 'itinerary' => 'ESTACAO DIAMANTE / OLARIA');
Bus::create('line' => 314, 'itinerary' => 'ESTACAO DIAMANTE/ESTACAO BARREIRO VIA SANTA HELENA');
Bus::create('line' => 315, 'itinerary' => 'ESTACAO BARREIRO / BARREIRO');
Bus::create('line' => 3150, 'itinerary' => 'REGINA-LINDEIA / BH SHOPPING VIA ANEL RODOVIARIO');
Bus::create('line' => 318, 'itinerary' => 'ESTACAO BARREIRO/JARDIM LIBERDADE VIA MILIONARIOS');
Bus::create('line' => 319, 'itinerary' => 'VILA CEMIG/CONJ.ESPERANCA');
Bus::create('line' => 32, 'itinerary' => 'ESTACAO BARREIRO/CENTRO-TAMOIOS');
Bus::create('line' => 320, 'itinerary' => 'ESCOLA ESTADUAL AMARO NEVES');
Bus::create('line' => 321, 'itinerary' => 'OLHOS D AGUA / PILAR');
Bus::create('line' => 325, 'itinerary' => 'ESTACAO BARREIRO / FLAVIO MARQUES LISBOA');
Bus::create('line' => 326, 'itinerary' => 'ESTACAO BARREIRO / VALE DO JATOBA');
Bus::create('line' => 327, 'itinerary' => 'ESTACAO BARREIRO / CARDOSO A');
Bus::create('line' => 328, 'itinerary' => 'ESTACAO BARREIRO / CARDOSO B');
Bus::create('line' => 329, 'itinerary' => 'ESTACAO BARREIRO / JATOBA');
Bus::create('line' => 33, 'itinerary' => 'ESTACAO BARREIRO/CENTRO-HOSPITAIS');
Bus::create('line' => 330, 'itinerary' => 'ESTACAO BARREIRO / INDEPENDENCIA');
Bus::create('line' => 3301A, 'itinerary' => 'SANTA TEREZINHA');
Bus::create('line' => 3301B, 'itinerary' => 'CASTELO');
Bus::create('line' => 3302A, 'itinerary' => 'NOVA PAMPULHA VIA ITAMARATI');
Bus::create('line' => 3302B, 'itinerary' => 'BRAUNAS VIA ITAMARATI');
Bus::create('line' => 3302D, 'itinerary' => 'BRAUNAS');
Bus::create('line' => 331, 'itinerary' => 'ESTACAO BARREIRO/CONJ.ANTONIO TEIXEIRA DIAS V.UPA');
Bus::create('line' => 332, 'itinerary' => 'ESTACAO BARREIRO / MILIONARIOS - BONSUCESSO');
Bus::create('line' => 335, 'itinerary' => 'ESTACAO BARREIRO / LINDEIA');
Bus::create('line' => 3350, 'itinerary' => 'EST.BARREIRO/EST.DIAMANTE');
Bus::create('line' => 336, 'itinerary' => 'HOSPITAL EDUARDO DE MENEZES / VILA BERNADETE');
Bus::create('line' => 337, 'itinerary' => 'ESTACAO BARREIRO / ITAIPU');
Bus::create('line' => 34, 'itinerary' => 'ESTACAO BARREIRO/VIA EXPRESSA');
Bus::create('line' => 340, 'itinerary' => 'ESTACAO BARREIRO / VILA MANGUEIRAS');
Bus::create('line' => 341, 'itinerary' => 'ESTACAO BARREIRO / ESTACAO DIAMANTE VIA SAUDE');
Bus::create('line' => 342, 'itinerary' => 'ESTACAO BARREIRO / SOLAR VIA ESTACAO DIAMANTE');
Bus::create('line' => 35, 'itinerary' => 'ESTACAO BARREIRO/CENTRO-VIA SANTOS DUMONT');
Bus::create('line' => 3501A, 'itinerary' => 'JARDIM ALVORADA/SAO MARCOS');
Bus::create('line' => 3501B, 'itinerary' => 'OURO PRETO 3A GLEBA/BAIRRO IPE VIA JD. MONTANHES');
Bus::create('line' => 3502, 'itinerary' => 'OURO PRETO/SAO GABRIEL');
Bus::create('line' => 3503A, 'itinerary' => 'SANTA TEREZINHA/SAO GABRIEL');
Bus::create('line' => 401, 'itinerary' => 'METRO CID.INDUSTRIAL/S.MARIA');
Bus::create('line' => 402, 'itinerary' => 'METRO CID.INDUSTRIAL/CAMARGOS');
Bus::create('line' => 4031, 'itinerary' => 'SANTA MARIA / HOSPITAIS');
Bus::create('line' => 4032, 'itinerary' => 'CAICARA /SAVASSI/ PCA. DA LIBERDADE');
Bus::create('line' => 4033, 'itinerary' => 'CAMARGOS/CENTRO');
Bus::create('line' => 4034, 'itinerary' => 'NOVO DOM BOSCO / SAVASSI VIA PADRE EUSTAQUIO');
Bus::create('line' => 404, 'itinerary' => 'JARDIM ALVORADA/AV.DOM PEDRO II');
Bus::create('line' => 4102, 'itinerary' => 'APARECIDA/SERRA');
Bus::create('line' => 4103, 'itinerary' => 'APARECIDA/MANGABEIRAS');
Bus::create('line' => 4106, 'itinerary' => 'SAO CRISTOVAO/SANTO ANTONIO');
Bus::create('line' => 4107, 'itinerary' => 'ALTO CAICARA/SERRA');
Bus::create('line' => 4108, 'itinerary' => 'PEDRO II/MANGABEIRAS');
Bus::create('line' => 4110, 'itinerary' => 'DOM CABRAL/BELVEDERE');
Bus::create('line' => 4111, 'itinerary' => 'DOM CABRAL/ANCHIETA');
Bus::create('line' => 4113, 'itinerary' => 'BOM JESUS/BELVEDERE');
Bus::create('line' => 4114, 'itinerary' => 'BONFIM / CENTRO');
Bus::create('line' => 4150, 'itinerary' => 'SHOPPING DEL REY/BH SHOPPING');
Bus::create('line' => 4201, 'itinerary' => 'ALTO CAICARA/NOVA CINTRA');
Bus::create('line' => 4205, 'itinerary' => 'ERMELINDA/SALGADO FILHO');
Bus::create('line' => 4403A, 'itinerary' => 'ZOOLOGICO VIA SERRANO');
Bus::create('line' => 4403C, 'itinerary' => 'RESIDENCIAL SARANDI');
Bus::create('line' => 4403D, 'itinerary' => 'URCA-CONFISCO');
Bus::create('line' => 4405, 'itinerary' => 'COQUEIROS');
Bus::create('line' => 4410, 'itinerary' => 'CELSO MACHADO VIA SARAMENHA/URCA');
Bus::create('line' => 4501, 'itinerary' => 'CALIFORNIA II / SAO PAULO');
Bus::create('line' => 4801A, 'itinerary' => 'JARDIM FILADELFIA/BOA VISTA A');
Bus::create('line' => 4802A, 'itinerary' => 'PINDORAMA/BOA VISTA');
Bus::create('line' => 503, 'itinerary' => 'ESTACAO SAO GABRIEL / APARECIDA / SANTA ROSA');
Bus::create('line' => 5031, 'itinerary' => 'SUZANA/SAVASSI-VIA UNIVERSITARIO');
Bus::create('line' => 504, 'itinerary' => 'ESTACAO SAO GABRIEL / SANTA ROSA / APARECIDA');
Bus::create('line' => 506, 'itinerary' => 'JARDIM ALVORADA/AV.ANTONIO CARLOS');
Bus::create('line' => 507, 'itinerary' => 'OURO PRETO / SHOPPING DEL REY');
Bus::create('line' => 5101, 'itinerary' => 'SUZANA/CRUZEIRO');
Bus::create('line' => 5102, 'itinerary' => 'UFMG/SANTO ANTONIO');
Bus::create('line' => 5201, 'itinerary' => 'DONA CLARA/BURITIS');
Bus::create('line' => 533, 'itinerary' => 'CASTELO / SHOPPING DEL REY');
Bus::create('line' => 535, 'itinerary' => 'XANGRILA VIA ITAMARATY / SHOPPING DEL REY');
Bus::create('line' => 5401, 'itinerary' => 'SAO LUIS/DOM CABRAL');
Bus::create('line' => 5502A, 'itinerary' => 'JARDIM VITORIA A');
Bus::create('line' => 5502B, 'itinerary' => 'CAPITAO EDUARDO');
Bus::create('line' => 5502C, 'itinerary' => 'POUSADA SANTO ANTONIO');
Bus::create('line' => 5503A, 'itinerary' => 'GOIANIA A');
Bus::create('line' => 5503B, 'itinerary' => 'GOIANIA B');
Bus::create('line' => 5506A, 'itinerary' => 'RIBEIRO DE ABREU');
Bus::create('line' => 5506B, 'itinerary' => 'RIBEIRO DE ABREU VIA CONJUNTO');
Bus::create('line' => 5506C, 'itinerary' => 'PAULO VI VIA RIBEIRO DE ABREU');
Bus::create('line' => 5507A, 'itinerary' => 'JARDIM GUANABARA A');
Bus::create('line' => 5513, 'itinerary' => 'JULIANA VIA ETELVINA CARNEIRO');
Bus::create('line' => 5517, 'itinerary' => 'MINAS CAIXA VIA SERRA VERDE');
Bus::create('line' => 5534, 'itinerary' => 'CONJUNTO ZILAH SPOSITO');
Bus::create('line' => 60, 'itinerary' => 'VENDA NOVA/CENTRO');
Bus::create('line' => 601, 'itinerary' => 'NOVA YORK / JULIANA');
Bus::create('line' => 6024, 'itinerary' => 'MARIA HELENA A/CENTRO');
Bus::create('line' => 6025, 'itinerary' => 'MARIA HELENA B / CENTRO');
Bus::create('line' => 6027, 'itinerary' => 'MANTIQUEIRA / CENTRO COM RETORNO EXPRESSO');
Bus::create('line' => 607, 'itinerary' => 'ESPLENDOR/JAQUELINE');
Bus::create('line' => 608, 'itinerary' => 'NOVA PAMPULHA/VENDA NOVA');
Bus::create('line' => 609, 'itinerary' => 'SERRA VERDE/SANTA MONICA');
Bus::create('line' => 61, 'itinerary' => 'ESTACAO VENDA NOVA/CENTRO-DIRETA');
Bus::create('line' => 62, 'itinerary' => 'ESTACAO VENDA NOVA/SAVASSI VIA HOSPITAIS');
Bus::create('line' => 621, 'itinerary' => 'ESTACAO VENDA NOVA / LAGOA');
Bus::create('line' => 622, 'itinerary' => 'ESTACAO VENDA NOVA / LAGOINHA');
Bus::create('line' => 623, 'itinerary' => 'ESTACAO VENDA NOVA / VILA SANTA BRANCA');
Bus::create('line' => 624, 'itinerary' => 'ESTACAO VENDA NOVA / MARIA HELENA A');
Bus::create('line' => 625, 'itinerary' => 'ESTACAO VENDA NOVA / MARIA HELENA B');
Bus::create('line' => 626, 'itinerary' => 'ESTACAO VENDA NOVA/ESPLENDOR VIA NOVA AMERICA');
Bus::create('line' => 627, 'itinerary' => 'ESTACAO VENDA NOVA/MANTIQUEIRA');
Bus::create('line' => 63, 'itinerary' => 'ESTACAO VENDA NOVA/LAGOINHA');
Bus::create('line' => 630, 'itinerary' => 'ESTACAO VENDA NOVA / SERRA VERDE V. AV. SALAMANCA');
Bus::create('line' => 631, 'itinerary' => 'ESTACAO VENDA NOVA / SERRA VERDE V. MINAS CAIXA');
Bus::create('line' => 633, 'itinerary' => 'ESTACAO VENDA NOVA/JARDIM DOS COMERCIARIOS');
Bus::create('line' => 634, 'itinerary' => 'EST. VILARINHO/NOVA YORK VIA JD.DOS COMERCIARIOS A');
Bus::create('line' => 635, 'itinerary' => 'ESTACAO VENDA NOVA / JARDIM DOS COMERCIARIOS C');
Bus::create('line' => 6350, 'itinerary' => 'EST.VILARINHO/EST.BARREIRO VIA ANEL RODOVIARIO');
Bus::create('line' => 636, 'itinerary' => 'ESTACAO VENDA NOVA / JARDIM EUROPA');
Bus::create('line' => 637, 'itinerary' => 'ESTACAO VILARINHO / CANAA VIA SERRA VERDE');
Bus::create('line' => 638, 'itinerary' => 'ESTACAO VILARINHO/MINAS CAIXA');
Bus::create('line' => 639, 'itinerary' => 'BRAUNAS / SHOPPING DEL REY');
Bus::create('line' => 64, 'itinerary' => 'ESTACAO VENDA NOVA/SANTO AGOSTINHO VIA CARLOS LUZ');
Bus::create('line' => 640, 'itinerary' => 'ESTACAO VENDA NOVA / JARDIM LEBLON VIA RIO BRANCO');
Bus::create('line' => 641, 'itinerary' => 'ESTACAO VILARINHO/SERRA VERDE');
Bus::create('line' => 642, 'itinerary' => 'VENDA NOVA/ESTACAO VILARINHO');
Bus::create('line' => 65, 'itinerary' => 'ESTACAO VILARINHO/CENTRO VIA ANTONIO CARLOS');
Bus::create('line' => 66, 'itinerary' => 'CIDADE ADMINISTRATIVA/SAVASSI VIA HOSPITAIS');
Bus::create('line' => 67, 'itinerary' => 'CIDADE ADMINISTRATIVA/STO AGOSTINHO VIA CARLOS LUZ');
Bus::create('line' => 702, 'itinerary' => 'ESTACAO SAO GABRIEL / XODO-MARIZE');
Bus::create('line' => 703, 'itinerary' => 'ESTACAO SAO GABRIEL / GUARANI A');
Bus::create('line' => 705, 'itinerary' => 'ESTACAO SAO GABRIEL / SAO TOMAZ');
Bus::create('line' => 706, 'itinerary' => 'ESTACAO SAO GABRIEL / HELIOPOLIS');
Bus::create('line' => 707, 'itinerary' => 'ESTACAO SAO GABRIEL / JARDIM GUANABARA');
Bus::create('line' => 708, 'itinerary' => 'ESTACAO SAO GABRIEL / FELICIDADE');
Bus::create('line' => 709, 'itinerary' => 'ESTACAO SAO GABRIEL / TUPI');
Bus::create('line' => 710, 'itinerary' => 'ESTACAO SAO GABRIEL / PROVIDENCIA');
Bus::create('line' => 711, 'itinerary' => 'ESTACAO SAO GABRIEL / SOLIMOES');
Bus::create('line' => 713, 'itinerary' => 'ESTACAO SAO GABRIEL / LAJEDO');
Bus::create('line' => 714, 'itinerary' => 'ESTACAO SAO GABRIEL / CASAS POPULARES');
Bus::create('line' => 715, 'itinerary' => 'ESTACAO SAO GABRIEL / MONTE AZUL');
Bus::create('line' => 716, 'itinerary' => 'ESTACAO SAO GABRIEL / NOVO AARAO REIS');
Bus::create('line' => 732, 'itinerary' => 'ESTACAO SAO GABRIEL / TUPI-FELICIDADE');
Bus::create('line' => 734, 'itinerary' => 'ESTACAO SAO GABRIEL / AARAO REIS VIA MINASLANDIA');
Bus::create('line' => 735, 'itinerary' => 'ESTACAO VILARINHO/JULIANA A');
Bus::create('line' => 736, 'itinerary' => 'ESTACAO VILARINHO/JULIANA B');
Bus::create('line' => 737, 'itinerary' => 'ESTACAO VILARINHO/JAQUELINE');
Bus::create('line' => 738, 'itinerary' => 'ESTACAO VILARINHO/CONJ.ZILAH SPOSITO');
Bus::create('line' => 739, 'itinerary' => 'ESTACAO VILARINHO/FREI LEOPOLDO VIA ZILAH SPOSITO');
Bus::create('line' => 741, 'itinerary' => 'ESTACAO VILARINHO/PLANALTO');
Bus::create('line' => 80, 'itinerary' => 'ESTACAO SAO GABRIEL/AV.CRISTIANO MACHADO');
Bus::create('line' => 8001A, 'itinerary' => 'SANTA INES/BH SHOPPING');
Bus::create('line' => 806, 'itinerary' => 'ESTACAO SAO GABRIEL / VISTA DO SOL VIA NAZARE');
Bus::create('line' => 807, 'itinerary' => 'ESTACAO SAO GABRIEL / RIBEIRO DE ABREU A');
Bus::create('line' => 808, 'itinerary' => 'ESTACAO SAO GABRIEL / PAULO VI');
Bus::create('line' => 809, 'itinerary' => 'ESTACAO SAO GABRIEL / BELMONTE');
Bus::create('line' => 81, 'itinerary' => 'ESTACAO SAO GABRIEL/HOSPITAIS VIA FLORESTA');
Bus::create('line' => 810, 'itinerary' => 'ESTACAO SAO GABRIEL/PARQUE BELMONTE VIA D.SILVERIO');
Bus::create('line' => 8101, 'itinerary' => 'SANTA CRUZ/ALTO SANTA LUCIA');
Bus::create('line' => 8102, 'itinerary' => 'UNIAO/CARMO SION');
Bus::create('line' => 8103, 'itinerary' => 'NOVA FLORESTA/SANTA LUCIA');
Bus::create('line' => 8106, 'itinerary' => 'SANTA CRUZ/BH SHOPPING VIA BELVEDERE');
Bus::create('line' => 8107, 'itinerary' => 'CONCORDIA/SAO PEDRO');
Bus::create('line' => 8108, 'itinerary' => 'CIDADE NOVA/SAVASSI');
Bus::create('line' => 811, 'itinerary' => 'ESTACAO SAO GABRIEL / VISTA DO SOL VIA PUC');
Bus::create('line' => 812, 'itinerary' => 'ESTACAO SAO GABRIEL / SAO GABRIEL A');
Bus::create('line' => 815, 'itinerary' => 'ESTACAO SAO GABRIEL / CONJUNTO PAULO VI');
Bus::create('line' => 8150, 'itinerary' => 'UNIAO/SERRA');
Bus::create('line' => 82, 'itinerary' => 'ESTACAO SAO GABRIEL / SAVASSI VIA HOSPITAIS');
Bus::create('line' => 8203, 'itinerary' => 'RENASCENCA/BURITIS');
Bus::create('line' => 8205, 'itinerary' => 'MARIA GORETTI/NOVA GRANADA VIA ALTO BARROCA');
Bus::create('line' => 8207, 'itinerary' => 'MARIA GORETTI/ESTRELA DALVA');
Bus::create('line' => 8208, 'itinerary' => 'SANTA CRUZ / UNI-ESTORIL');
Bus::create('line' => 821, 'itinerary' => 'ESTACAO JOSE CANDIDO / GOIANIA');
Bus::create('line' => 822, 'itinerary' => 'ESTACAO JOSE CANDIDO/VILA MARIA');
Bus::create('line' => 823, 'itinerary' => 'ESTACAO SAO GABRIEL / BAIRRO VITORIA');
Bus::create('line' => 832, 'itinerary' => 'ESTACAO SAO GABRIEL / CAPITAO EDUARDO');
Bus::create('line' => 8350, 'itinerary' => 'ESTACAO SAO GABRIEL/ESTACAO BARREIRO');
Bus::create('line' => 836, 'itinerary' => 'ESTACAO SAO GABRIEL / RIBEIRO DE ABREU B');
Bus::create('line' => 837, 'itinerary' => 'ESTACAO SAO GABRIEL / CONJUNTO RIBEIRO DE ABREU');
Bus::create('line' => 83D, 'itinerary' => 'ESTACAO SAO GABRIEL / CENTRO - DIRETA');
Bus::create('line' => 83P, 'itinerary' => 'ESTACAO SAO GABRIEL / CENTRO - PARADORA');
Bus::create('line' => 8401, 'itinerary' => 'CACHOEIRINHA/SAO JOSE');
Bus::create('line' => 8405, 'itinerary' => 'PALMARES/BELA VISTA');
Bus::create('line' => 8501, 'itinerary' => 'MARIA GORETTI/ENGENHO NOGUEIRA VIA OURO PRETO');
Bus::create('line' => 8550, 'itinerary' => 'ESTACAO SAO GABRIEL/ZOOLOGICO');
Bus::create('line' => 901, 'itinerary' => 'CIRCULAR LESTE');
Bus::create('line' => 9030, 'itinerary' => 'CASTANHEIRAS/CENTRO');
Bus::create('line' => 9031, 'itinerary' => 'NOSSA SENHORA DE FATIMA/CENTRO');
Bus::create('line' => 9032, 'itinerary' => 'GRANJA DE FREITAS');
Bus::create('line' => 9101, 'itinerary' => 'ALTO VERA CRUZ/SANTA LUCIA');
Bus::create('line' => 9103, 'itinerary' => 'SANTA TERESA/SANTO ANTONIO');
Bus::create('line' => 9104, 'itinerary' => 'SAGRADA FAMILIA/LUXEMBURGO');
Bus::create('line' => 9105, 'itinerary' => 'NOVA VISTA/SION');
Bus::create('line' => 9106, 'itinerary' => 'SAGRADA FAMILIA/SERRA');
Bus::create('line' => 9201, 'itinerary' => 'BALEIA/NOVA GRANADA');
Bus::create('line' => 9202, 'itinerary' => 'POMPEIA/JARDIM AMERICA');
Bus::create('line' => 9204, 'itinerary' => 'SANTA EFIGENIA/ESTORIL');
Bus::create('line' => 9205, 'itinerary' => 'NOVA VISTA/NOVA CINTRA');
Bus::create('line' => 9206, 'itinerary' => 'VERA CRUZ/BURITIS');
Bus::create('line' => 9208, 'itinerary' => 'TAQUARIL/CONJUNTO SANTA MARIA');
Bus::create('line' => 9209, 'itinerary' => 'SAGRADA FAMILIA/GUTIERREZ');
Bus::create('line' => 9210, 'itinerary' => 'SANTA TERESA/PRADO');
Bus::create('line' => 9211, 'itinerary' => 'CAETANO FURQUIM/HAVAI');
Bus::create('line' => 9214, 'itinerary' => 'CAETANO FURQUIM / HAVAI - VIA ALTO HAVAI');
Bus::create('line' => 9250, 'itinerary' => 'CAETANO FURQUIM/NOVA CINTRA VIA SAVASSI');
Bus::create('line' => 9402, 'itinerary' => 'SANTA INES/SANTO ANDRE');
Bus::create('line' => 9403, 'itinerary' => 'PARAISO/CAICARA');
Bus::create('line' => 9404, 'itinerary' => 'SAO LUCAS/NOVA ESPERANCA');
Bus::create('line' => 9405, 'itinerary' => 'INSTITUTO AGRONOMICO/MONSENHOR MESSIAS');
Bus::create('line' => 9407, 'itinerary' => 'ALTO VERA CRUZ/DOM BOSCO');
Bus::create('line' => 9408, 'itinerary' => 'SANTA EFIGENIA/PADRE EUSTAQUIO');
Bus::create('line' => 9410, 'itinerary' => 'SAGRADA FAMILIA/CORACAO EUCARISTICO');
Bus::create('line' => 9411, 'itinerary' => 'CASA BRANCA/SAO JOSE');
Bus::create('line' => 9412, 'itinerary' => 'CONJ.TAQUARIL/PADRE EUSTAQUIO');
Bus::create('line' => 9414, 'itinerary' => 'SANTA INES/JOAO PINHEIRO');
Bus::create('line' => 9501, 'itinerary' => 'SAO LUCAS/JARAGUA');
Bus::create('line' => 9502, 'itinerary' => 'SAO GERALDO/SAO FRANCISCO VIA ESPLANADA');
Bus::create('line' => 9503, 'itinerary' => 'TAQUARIL/JARAGUA');
Bus::create('line' => 9550, 'itinerary' => 'CASA BRANCA/SAO FRANCISCO VIA EST. JOSE CANDIDO');
Bus::create('line' => 9801, 'itinerary' => 'SAUDADE/SANTA CRUZ');
Bus::create('line' => 9803, 'itinerary' => 'TAQUARIL/PALMARES');
Bus::create('line' => 9805, 'itinerary' => 'SANTA EFIGENIA/RENASCENCA');
Bus::create('line' => 9850, 'itinerary' => 'ESTACAO JOSE CANDIDO / ESTACAO SAO GABRIEL');
Bus::create('line' => S10, 'itinerary' => 'BH SHOPPING / SAO FRANCISCO');
Bus::create('line' => S20, 'itinerary' => 'PALMEIRAS / SERRA');
Bus::create('line' => S21, 'itinerary' => 'DOM CABRAL / BH SHOPPING');
Bus::create('line' => S22, 'itinerary' => 'BURITIS / METRO CALAFATE');
Bus::create('line' => S31, 'itinerary' => 'PETROPOLIS / BAIRRO DAS INDUSTRIAS');
Bus::create('line' => S32, 'itinerary' => 'ITAIPU / CARDOSO');
Bus::create('line' => S33, 'itinerary' => 'LINDEIA / MILIONARIOS');
Bus::create('line' => S41, 'itinerary' => 'CONJUNTO CALIFORNIA / PRADO');
Bus::create('line' => S50, 'itinerary' => 'CAICARA / NOVA VISTA VIA UFMG');
Bus::create('line' => S51, 'itinerary' => 'CIRCULAR PAMPULHA');
Bus::create('line' => S52, 'itinerary' => 'CIRCULAR PAMPULHA');
Bus::create('line' => S53, 'itinerary' => 'CONFISCO / OURO MINAS');
Bus::create('line' => S54, 'itinerary' => 'DOM BOSCO / SHOPPING DEL REY');
Bus::create('line' => S55, 'itinerary' => 'SANTA MONICA / MINAS SHOPPING');
Bus::create('line' => S60, 'itinerary' => 'CIRCULAR VENDA NOVA');
Bus::create('line' => S61, 'itinerary' => 'LANDI / ESTACAO VILARINHO');
Bus::create('line' => S63, 'itinerary' => 'CIRCULAR VENDA NOVA');
Bus::create('line' => S64, 'itinerary' => 'CIRCULAR VENDA NOVA');
Bus::create('line' => S65, 'itinerary' => 'SAO BERNARDO / MINAS CAIXA');
Bus::create('line' => S66, 'itinerary' => 'TUPI / EUROPA');
Bus::create('line' => S70, 'itinerary' => 'CONJ. FELICIDADE / SHOPPING DEL REY');
Bus::create('line' => S80, 'itinerary' => 'JARDIM VITORIA / VIADUTO CIDADE INDUSTRIAL');
Bus::create('line' => S81, 'itinerary' => 'CIRCULAR NORDESTE');
Bus::create('line' => S82, 'itinerary' => 'CIRCULAR NORDESTE');
Bus::create('line' => S85, 'itinerary' => 'MINAS SHOPPING / SANTA INES');
Bus::create('line' => SC01A, 'itinerary' => 'CONTORNO A');
Bus::create('line' => SC01B, 'itinerary' => 'CONTORNO B');
Bus::create('line' => SC01R, 'itinerary' => 'CONTORNO/PRACA MILTON CAMPOS');
Bus::create('line' => SC02A, 'itinerary' => 'PRACA 7/SAVASSI VIA PCA DA LIBERDADE - SANTA CASA');
Bus::create('line' => SC02B, 'itinerary' => 'SAVASSI/PRACA 7 VIA SANTA CASA - PCA DA LIBERDADE');
Bus::create('line' => SC03A, 'itinerary' => 'HOSPITAL FELICIO ROCHO/HOSPITAL MILITAR A');
Bus::create('line' => SC03B, 'itinerary' => 'HOSPITAL FELICIO ROCHO/HOSPITAL MILITAR B');
Bus::create('line' => SC04A, 'itinerary' => 'SANTA CASA/SAVASSI/RODOVIARIA A');
Bus::create('line' => SC04B, 'itinerary' => 'SANTA CASA/RODOVIARIA/SAVASSI B');
Bus::create('line' => SE01, 'itinerary' => 'CIDADE ADMINISTRATIVA/SAVASSI');
Bus::create('line' => SE02, 'itinerary' => 'BURITIS/SAVASSI');