<?php

class DERTableSeeder extends Seeder {

    public function run()
    {
        Bus::create(["line" => "E1910", "itinerary" => "ATENDIMENTO EMERGENCIAL ESTAÇÃO ELDORADO/BH"]);
        Bus::create(["line" => "E1925", "itinerary" => "ATENDIMENTO EMERGENCIAL ESTAÇÃO ELDORADO/BH"]);
        Bus::create(["line" => "1000", "itinerary" => "TERM. TANCREDO NEVES/BAIRRO REGINA/BARREIRO/ALAMEDA DA SERRA"]);
        Bus::create(["line" => "1100", "itinerary" => "TERM. TANCREDO NEVES/PALMARES VIA J. C. OLIVEIRA/BELA VISTA"]);
        Bus::create(["line" => "1110", "itinerary" => "TERM. TANCREDO NEVES/WASHINGTON PIRES/LINDEIAL/B.HTE."]);
        Bus::create(["line" => "1111", "itinerary" => "TERMINAL TANCREDO NEVES/W.PIRES/B.AMAZONAS/BH"]);
        Bus::create(["line" => "1120", "itinerary" => "TERMINAL TANCREDO NEVES/SOL NASCENTE/TIROL/BELO HORIZONTE"]);
        Bus::create(["line" => "1130", "itinerary" => "TERMINAL TANCREDO NEVES/PALMARES 1a. SECAO/BELO HORIZONTE"]);
        Bus::create(["line" => "1140", "itinerary" => "TERMINAL TANCREDO NEVES/PALMARES 2a. SECAO/BELO HORIZONTE"]);
        Bus::create(["line" => "1150", "itinerary" => "TERM. TANCREDO NEVES/DUVAL DE BARROS/FLAMENGO/BELO HORIZONTE"]);
        Bus::create(["line" => "1180", "itinerary" => "VILA IDEAL/TERMINAL TANCREDO NEVES"]);
        Bus::create(["line" => "1190", "itinerary" => "PALMARES/TERMINAL TANCREDO NEVES"]);
        Bus::create(["line" => "1191", "itinerary" => "PALMEIRAS/GUANABARA/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "1200", "itinerary" => "BAIRRO LAJINHA/TERMINAL TANCREDO NEVES"]);
        Bus::create(["line" => "1210", "itinerary" => "JATOBA/SOL NASCENTE /TERMINAL TANCREDO NEVES"]);
        Bus::create(["line" => "1220", "itinerary" => "TERM. TANC. NEVES/SOL NASCENTE VIA J. C. OLIVEIRA/BELA VISTA"]);
        Bus::create(["line" => "1230", "itinerary" => "TERMINAL TANCREDO NEVES VIA BR-381/MONTE CASTELO"]);
        Bus::create(["line" => "1240", "itinerary" => "PALMARES 2a. SECAO/TERMINAL TANCREDO NEVES"]);
        Bus::create(["line" => "1250", "itinerary" => "AGUA BRANCA/JATOBA "]);
        Bus::create(["line" => "1260", "itinerary" => "DUVAL DE BARROS/PALMARES/SOL NASCENTE/EST. DIAMANTE"]);
        Bus::create(["line" => "1270", "itinerary" => "REGINA/LINDEIA/BELO HORIZONTE"]);
        Bus::create(["line" => "1280", "itinerary" => "LINDEIA VIA CID.INDUSTRIAL/BELO HORIZONTE"]);
        Bus::create(["line" => "1290", "itinerary" => "VILA IDEAL /ESTACAO DIAMANTE"]);
        Bus::create(["line" => "1300", "itinerary" => "PALMARES 2a. SECAO VIA AV. JOAO CESAR DE OLIVEIRA/BELA VISTA"]);
        Bus::create(["line" => "1310", "itinerary" => "SOL NASCENTE VIA PCA. MINERVA/BELO HORIZONTE"]);
        Bus::create(["line" => "1320", "itinerary" => "CIDADE INDUSTRIAL/ALAMEDA DA SERRA"]);
        Bus::create(["line" => "1330", "itinerary" => "WASHINGTON PIRES/JOAO PINHEIRO"]);
        Bus::create(["line" => "1340", "itinerary" => "FLAMENGO/VALE DO JATOBA I"]);
        Bus::create(["line" => "1350", "itinerary" => "FLAMENGO/MANGUEIRAS I"]);
        Bus::create(["line" => "1360", "itinerary" => "INDUSTRIAL VIA JARDIM INDUSTRIAL/BELO HORIZONTE"]);
        Bus::create(["line" => "1370", "itinerary" => "INDUSTRIAL/CARDOSO A"]);
        Bus::create(["line" => "1380", "itinerary" => "INDUSTRIAL/CARDOSO B"]);
        Bus::create(["line" => "1390", "itinerary" => "BAIRRO AMAZONAS/BELO HORIZONTE"]);
        Bus::create(["line" => "1600", "itinerary" => "PETROLINA/ESTACAO ELDORADO "]);
        Bus::create(["line" => "1610", "itinerary" => "MONTREAL VIA OURO NEGRO/BELO HORIZONTE"]);
        Bus::create(["line" => "1620", "itinerary" => "JARDIM DAS ROSAS VIA BR-381/ESTACAO ELDORADO "]);
        Bus::create(["line" => "1630", "itinerary" => "CASCATA/ESTACAO ELDORADO "]);
        Bus::create(["line" => "1640", "itinerary" => "OURO NEGRO/ESTACAO ELDORADO "]);
        Bus::create(["line" => "1650", "itinerary" => "MONTREAL VIA OURO NEGRO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "1660", "itinerary" => "MONTREAL VIA OURO NEGRO/BELO HORIZONTE"]);
        Bus::create(["line" => "1670", "itinerary" => "MONTREAL/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "1680", "itinerary" => "PETROVALE/BELO HORIZONTE"]);
        Bus::create(["line" => "1690", "itinerary" => "CASCATA/BELO HORIZONTE"]);
        Bus::create(["line" => "1700", "itinerary" => "BAIRRO ELDORADO VIA BR-381/ESTACAO ELDORADO"]);
        Bus::create(["line" => "1710", "itinerary" => "PETROVALE/ESTACAO ELDORADO "]);
        Bus::create(["line" => "1720", "itinerary" => "RECANTO DA LAGOA/MONTREAL/OURO NEGRO/PETROVALE/B.HTE."]);
        Bus::create(["line" => "1730", "itinerary" => "ESTACAO DIAMANTE/CONTAGEM/ALVORADA"]);
        Bus::create(["line" => "1740", "itinerary" => "CONTAGEM/ESTACAO DIAMANTE "]);
        Bus::create(["line" => "1750", "itinerary" => "AGUIA DOURADA/ESTACAO DIAMANTE "]);
        Bus::create(["line" => "1751", "itinerary" => "VISTA ALEGRE/ESTAÇÃO BARREIRO"]);
        Bus::create(["line" => "1760", "itinerary" => "MILIONARIOS/MAKRO"]);
        Bus::create(["line" => "1770", "itinerary" => "NOSSA SENHORA DE LOURDES/ESTACAO DIAMANTE "]);
        Bus::create(["line" => "1771", "itinerary" => "NOSSA SENHORA DE LOURDES/ESTAÇÃO BARREIRO"]);
        Bus::create(["line" => "1900", "itinerary" => "FLAMENGO/BELO HORIZONTE"]);
        Bus::create(["line" => "1910", "itinerary" => "DISTRITO INDUSTRIAL DO B. JARDIM RIACHO DAS PEDRAS/B.HTE."]);
        Bus::create(["line" => "1950", "itinerary" => "OLARIA VIA CONJUNTO ANTONIO TEIXEIRA DIAS/GLORIA"]);
        Bus::create(["line" => "1980", "itinerary" => "MORADA DA SERRA/ESTACAO BARREIRO"]);
        Bus::create(["line" => "2100", "itinerary" => "JARDIM LAGUNA VIA NOVO PROGRESSO/RETORNO PRACA DO VATICANO"]);
        Bus::create(["line" => "2110", "itinerary" => "JARDIM LAGUNA C VIA NOVO PROGRESSO/BELO HORIZONTE"]);
        Bus::create(["line" => "2120", "itinerary" => "JARDIM LAGUNA C VIA AV. JOAO GOMES/PARQUE AYRTON SENNA/BH"]);
        Bus::create(["line" => "2130", "itinerary" => "JARDIM LAGUNA/BELO HORIZONTE"]);
        Bus::create(["line" => "2140", "itinerary" => "JARDIM LAGUNA/BELO HORIZONTE VIA AVENIDA CATALAO"]);
        Bus::create(["line" => "2150", "itinerary" => "NOVO CEU VIA OITIS/BELO HORIZONTE "]);
        Bus::create(["line" => "2160", "itinerary" => "NOVO CEU/BELO HORIZONTE "]);
        Bus::create(["line" => "2170", "itinerary" => "JARDIM LAGUNA VIA NOVO PROGRESSO/BELO HORIZONTE"]);
        Bus::create(["line" => "2180", "itinerary" => "JARDIM LAGUNA VIA AV. BRIGADEIRO EDUARDO GOMES/B.HTE."]);
        Bus::create(["line" => "2190", "itinerary" => "AGUA BRANCA/BELO HORIZONTE"]);
        Bus::create(["line" => "2200", "itinerary" => "DARCY VARGAS/BELO HORIZONTE"]);
        Bus::create(["line" => "2210", "itinerary" => "DARCI VARGAS VIA CONJUNTO AGUA BRANCA/BELO HORIZONTE"]);
        Bus::create(["line" => "2250", "itinerary" => "GUANABARA VIA JARDIM PEROLA/BELO HORIZONTE"]);
        Bus::create(["line" => "2260", "itinerary" => "GUANABARA VIA AV. BRIGADEIRO EDUARDO GOMES/BELO HORIZONTE"]);
        Bus::create(["line" => "2270", "itinerary" => "SAO JOAQUIM VIA PARQUE RECREIO/BELO HORIZONTE"]);
        Bus::create(["line" => "2280", "itinerary" => "SAO JOAQUIM VIA AV. BRIGADEIRO EDUARDO GOMES/BELO HORIZONTE"]);
        Bus::create(["line" => "2290", "itinerary" => "BAIRRO NACIONAL/BELO HORIZONTE"]);
        Bus::create(["line" => "2291", "itinerary" => "BAIRRO NACIONAL / BH / RETORNO PRAÇA SÃO VICENTE"]);
        Bus::create(["line" => "2300", "itinerary" => "JARDIM ALVORADA/BELO HORIZONTE"]);
        Bus::create(["line" => "2310", "itinerary" => "NACIONAL/BOM JESUS VIA BR-040/BELO HORIZONTE"]);
        Bus::create(["line" => "2320", "itinerary" => "NACIONAL AV. BRIGADEIRO EDUARDO GOMES/BELO HORIZONTE"]);
        Bus::create(["line" => "2330", "itinerary" => "XANGRILA/BELO HORIZONTE"]);
        Bus::create(["line" => "2340", "itinerary" => "BAIRRO NACIONAL/RETORNO  PRACA DO VATICANO"]);
        Bus::create(["line" => "2350", "itinerary" => "CONJUNTO CARAJAS/BELO HORIZONTE"]);
        Bus::create(["line" => "2360", "itinerary" => "VALE DAS AMENDOEIRAS - N.SRA. CONCEICAO/BELO HORIZONTE"]);
        Bus::create(["line" => "2370", "itinerary" => "CLUBE CAMPESTRE DOS RODOVIARIOS A/BELO HORIZONTE"]);
        Bus::create(["line" => "2380", "itinerary" => "SUB-PREFEITURA - BAIRRO NACIONAL VIA BR 040/BELO HORIZONTE"]);
        Bus::create(["line" => "2381", "itinerary" => "JARDIM ALVORADA VIA BR 040/BELO HORIZONTE"]);
        Bus::create(["line" => "2390", "itinerary" => "CEASA VIA RESSACA/BELO HORIZONTE"]);
        Bus::create(["line" => "2391", "itinerary" => "BAIRRO CANDIDA FERREIRA VIA CABRAL / BH"]);
        Bus::create(["line" => "2400", "itinerary" => "CEASA VIA AV. BRIGADEIRO EDUARDO GOMES/BELO HORIZONTE"]);
        Bus::create(["line" => "2410", "itinerary" => "CEASA VIA DIST. INDUSTRIAL/BELO HORIZONTE "]);
        Bus::create(["line" => "2420", "itinerary" => "JARDIM DO LAGO VIA RESSACA/BELO HORIZONTE"]);
        Bus::create(["line" => "2430", "itinerary" => "JARDIM DO LAGO VIA AV. BRIGADEIRO EDUARDO GOMES/B.HTE."]);
        Bus::create(["line" => "2440", "itinerary" => "CAMPINA VERDE VIA CEASA/BELO HORIZONTE"]);
        Bus::create(["line" => "2450", "itinerary" => "CAMPINA VERDE/VIA EXPRESSA/BELO HORIZONTE"]);
        Bus::create(["line" => "2460", "itinerary" => "ALIPIO DE MELO VIA RESSACA/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "2470", "itinerary" => "RESSACA/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "2480", "itinerary" => "SAO JOSE/CIDADE INDUSTRIAL "]);
        Bus::create(["line" => "2490", "itinerary" => "ALIPIO DE MELO VIA AV. HELENA VASCONCELOS/CIDADE INDUSTRIAL "]);
        Bus::create(["line" => "2550", "itinerary" => "CONTAGEM/ALVORADA/BELO HORIZONTE"]);
        Bus::create(["line" => "2551", "itinerary" => "VILA BELÉM/BH VIA BERNARDO MONTEIRO"]);
        Bus::create(["line" => "2560", "itinerary" => "CONTAGEM VIA AV. HELENA VASCONCELOS/ALVORADA/BELO HORIZONTE"]);
        Bus::create(["line" => "2570", "itinerary" => "CONTAGEM/CANADA/BELO HORIZONTE"]);
        Bus::create(["line" => "2580", "itinerary" => "ELDORADO/BELO HORIZONTE"]);
        Bus::create(["line" => "2581", "itinerary" => "ELDORADO/BELO HORIZONTE-COMERCIAL EXECUTIVO"]);
        Bus::create(["line" => "2590", "itinerary" => "VILA CRISTINA / ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "2600", "itinerary" => "DUQUE DE CAXIAS/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "2700", "itinerary" => "BERNARDO MONTEIRO VIA CANADA/BELO HORIZONTE"]);
        Bus::create(["line" => "2710", "itinerary" => "SANTA HELENA/MARIA DA CONCEICAO"]);
        Bus::create(["line" => "2720", "itinerary" => "SANTA HELENA/MARIA DA CONCEICAO/BARREIRO"]);
        Bus::create(["line" => "2730", "itinerary" => "FONTE GRANDE/ESTACAO DIAMANTE"]);
        Bus::create(["line" => "2740", "itinerary" => "PARQUE SAO JOAO/BELO HORIZONTE"]);
        Bus::create(["line" => "2750", "itinerary" => "PARQUE SAO JOAO - VIA EXPRESSA/BELO HORIZONTE"]);
        Bus::create(["line" => "2760", "itinerary" => "GRANJAS VISTA ALEGRE VIA LINDA VISTA/BELO HORIZONTE"]);
        Bus::create(["line" => "2800", "itinerary" => "CONJUNTO CONFISCO/BELO HORIZONTE"]);
        Bus::create(["line" => "2810", "itinerary" => "SAO MATEUS VIA ESTRELA DALVA/BELO HORIZONTE"]);
        Bus::create(["line" => "2811", "itinerary" => "SÃO MATEUS VIA TIJUCA / BH"]);
        Bus::create(["line" => "2820", "itinerary" => "BAIRRO TIJUCA/BELO HORIZONTE"]);
        Bus::create(["line" => "2830", "itinerary" => "SAO MATEUS VIA AV. BRIGADEIRO EDUARDO GOMES/BELO HORIZONTE"]);
        Bus::create(["line" => "2880", "itinerary" => "PINDORAMA/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "2890", "itinerary" => "MORADA NOVA/MILANEZ/COLORADO"]);
        Bus::create(["line" => "2900", "itinerary" => "PINDORAMA VIA AV. IVAI - E. DOM BOSCO /CIDADE INDUSTRIAL "]);
        Bus::create(["line" => "2910", "itinerary" => "MORADA NOVA/MILANES/COLORADO/BELO HORIZONTE"]);
        Bus::create(["line" => "2920", "itinerary" => "MORADA NOVA/B.HTE. - E. E. PROF. LIGIA MARIA MAGALHAES"]);
        Bus::create(["line" => "2950", "itinerary" => "GLORIA VIA JK/BELO HORIZONTE"]);
        Bus::create(["line" => "2980", "itinerary" => "ELDORADO/VISTA ALEGRE"]);
        Bus::create(["line" => "3000", "itinerary" => "TERMINAL BETIM/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "3040", "itinerary" => "LAGO AZUL/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3100", "itinerary" => "TAQUARIL VIA NOSSA SRA. DAS GRACAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3105", "itinerary" => "HOMERO GIL VIA AV. AMERICAS/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3110", "itinerary" => "TAQUARIL/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "3115", "itinerary" => "CONJUNTO OLIMPIA BUENO FRANCO VIA DUQUE CAXIAS/B.HTE."]);
        Bus::create(["line" => "3120", "itinerary" => "BAIRRO ITACOLOMI/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3125", "itinerary" => "VILA DAS FLORES VIA NOVA BADEN/BELO HORIZONTE"]);
        Bus::create(["line" => "3126", "itinerary" => "VILA DAS FLORES/BELO HORIZONTE "]);
        Bus::create(["line" => "3130", "itinerary" => "BAIRRO LARANJEIRAS VIA DUQUE DE CAXIAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3135", "itinerary" => "CONJUNTO VARZEA DAS FLORES/BELO HORIZONTE"]);
        Bus::create(["line" => "3140", "itinerary" => "CRUZEIRO DO SUL/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3145", "itinerary" => "DUQUE DE CAXIAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3150", "itinerary" => " PARQUE DAS INDUSTRIAS/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3155", "itinerary" => "JD.ALTEROSAS 2ª SEÇÃO VIA LARANJEIRAS/BH"]);
        Bus::create(["line" => "3160", "itinerary" => "SITIO DAS POCOES/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3165", "itinerary" => "JARDIM DAS ALTEROSAS - RUA FALCATAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3170", "itinerary" => "PTB/BELO HORIZONTE"]);
        Bus::create(["line" => "3175", "itinerary" => "CRUZEIRO/BELO HORIZONTE VIA CAMPOS ELISEOS/PTB"]);
        Bus::create(["line" => "3180", "itinerary" => "CRUZEIRO VIA PTB/BELO HORIZONTE"]);
        Bus::create(["line" => "3185", "itinerary" => "CRUZEIRO VIA GUANABARA II/BELO HORIZONTE"]);
        Bus::create(["line" => "3186", "itinerary" => "ESTÂNCIAS DO SERENO/BH VIA PTB"]);
        Bus::create(["line" => "3190", "itinerary" => "CRUZEIRO VIA CAMPOS ELISEOS/BELO HORIZONTE"]);
        Bus::create(["line" => "3195", "itinerary" => "CRUZEIRO VIA JOVELINO GREGORIO/BELO HORIZONTE"]);
        Bus::create(["line" => "3200", "itinerary" => "VILA VERDE/ESTAÇÃO ELDORADO VIA CONJ. JOSÉ GOMES"]);
        Bus::create(["line" => "3205", "itinerary" => "CRUZEIRO/CAMPOS ELISEOS/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3210", "itinerary" => "BETIM/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3211", "itinerary" => "BETIM / CIDADE INDUSTRIAL VIA BAMBAS"]);
        Bus::create(["line" => "3212", "itinerary" => "BETIM/BELO HORIZONTE (VIP EXPRESS)"]);
        Bus::create(["line" => "3213", "itinerary" => "BETIM/AEROPORTO INTER.TANCREDO NEVES VIA AER. DA PAMPULHA"]);
        Bus::create(["line" => "3215", "itinerary" => "BANDEIRINHAS/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3220", "itinerary" => "BANDEIRINHAS VIA GRANJA SAO JOAO/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3225", "itinerary" => "MORADA DO TREVO VIA CIDADE VERDE/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3230", "itinerary" => "BETIM / BUENO FRANCO / CARREFOUR"]);
        Bus::create(["line" => "3231", "itinerary" => "BETIM / CARREFOUR VIA PIEMONT"]);
        Bus::create(["line" => "3232", "itinerary" => "CARREFOUR/ VILA VERDE"]);
        Bus::create(["line" => "3235", "itinerary" => "BETIM/MARIO CAMPOS"]);
        Bus::create(["line" => "3240", "itinerary" => "BETIM/ESTAÇÃO ELDORADO VIA MORADA DO TREVO"]);
        Bus::create(["line" => "3245", "itinerary" => "BETIM VIA AV. AMERICA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3250", "itinerary" => "GRANJAS SAO JOAO/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3255", "itinerary" => "JARDIM DAS ALTEROSAS/CIDADE INDUSTRIAL "]);
        Bus::create(["line" => "3260", "itinerary" => "RUA FALCATAS/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3265", "itinerary" => "CONJUNTO OLIMPIA BUENO FRANCO/BELO HORIZONTE"]);
        Bus::create(["line" => "3270", "itinerary" => "HOMERO GIL/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3275", "itinerary" => "PARQUE DAS INDÚSTRIAS/ESTAÇÃO ELDORADO "]);
        Bus::create(["line" => "3280", "itinerary" => "JARDIM DAS ALTEROSAS  2a. SECAO/BELO HORIZONTE"]);
        Bus::create(["line" => "3285", "itinerary" => "BUENO FRANCO/BELO HORIZONTE - VIA ALTEROSAS 2ª SEÇÃO"]);
        Bus::create(["line" => "3290", "itinerary" => " NOSSA SENHORA DAS GRACAS/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3291", "itinerary" => "PINGO D'ÁGUA/BELO HORIZONTE"]);
        Bus::create(["line" => "3292", "itinerary" => "BETIM/BELO HORIZONTE"]);
        Bus::create(["line" => "3293", "itinerary" => "BETIM VIA CIDADE VERDE/BELO HORIZONTE"]);
        Bus::create(["line" => "3297", "itinerary" => "BETIM/BELO HORIZONTE - VIA RESIDENCIAL LAGOA"]);
        Bus::create(["line" => "3298", "itinerary" => "PUC BETIM/BELO HORIZONTE"]);
        Bus::create(["line" => "3303", "itinerary" => "BOM RETIRO/BELO HORIZONTE VIA VIA EXPRESSA"]);
        Bus::create(["line" => "3304", "itinerary" => "SENHORA DAS GRAÇAS - NOVA BADEN/BELO HORIZONTE VIA EXPRESSA"]);
        Bus::create(["line" => "3305", "itinerary" => "VÁRZEA DAS FLORES/BELO HORIZONTE VIA EXPRESSA "]);
        Bus::create(["line" => "3306", "itinerary" => "HOMERO GIL/BELO HORIZONTE VIA VIA EXPRESSA"]);
        Bus::create(["line" => "3307", "itinerary" => "BETIM VIA AV. BANDEIRANTES/BELO HORIZONTE"]);
        Bus::create(["line" => "3308", "itinerary" => "SÃO JOÃO VIA JARDIM PETRÓPOLIS/BELO HORIZONTE"]);
        Bus::create(["line" => "3328", "itinerary" => "NOSSA SENHORA DA PAZ/S.JOAQUIM DE BICAS/V. RICA/EST.ELDORADO"]);
        Bus::create(["line" => "3332", "itinerary" => "IGARAPE VIA MAGNA SEATING/BELO HORIZONTE"]);
        Bus::create(["line" => "3333", "itinerary" => "IGARAPE VIA ROSEIRA/BELO HORIZONTE"]);
        Bus::create(["line" => "3334", "itinerary" => "POUSADA DEL REY / BELO HORIZONTE"]);
        Bus::create(["line" => "3336", "itinerary" => "NOSSA SENHORA DA PAZ/S.JOAQUIM DE BICAS VIA MAGNA SEATING/BH"]);
        Bus::create(["line" => "3337", "itinerary" => "IGARAPE VIA RESPLENDOR/BELO HORIZONTE"]);
        Bus::create(["line" => "3338", "itinerary" => "IGARAPE VIA MAGNA SEATING/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3339", "itinerary" => "IGARAPÉ/VIA RESPLENDOR/VIA MAGNA SEATING/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "3341", "itinerary" => "S.J.DE BICAS/V.RICA V.M.SEATING/P.BRANCA/BETIM/AT. S.MINEIRO"]);
        Bus::create(["line" => "3342", "itinerary" => "SAO JOAQUIM DE BICAS VIA MAGNA SEATING/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3343", "itinerary" => "IGARAPE VIA BR 381/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3344", "itinerary" => "IGARAPÉ VIA ROSEIRA/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "3345", "itinerary" => "IGARAPÉ VIA ROSEIRA/BETIM/ATEND. SUPERMERCADO MINEIRO"]);
        Bus::create(["line" => "3346", "itinerary" => "IGARAPÉ VIA ROSEIRA/BETIM"]);
        Bus::create(["line" => "3347", "itinerary" => "IGARAPE/BETIM /ATEND. SUPERMERCADO MINEIRO"]);
        Bus::create(["line" => "3348", "itinerary" => "IGARAPÉ VIA MAGNA SEATING/BETIM"]);
        Bus::create(["line" => "3349", "itinerary" => "S. J. DE BICAS/V. RICA VIA M. SEATING/BETIM/AT. SUP.MINEIRO   "]);
        Bus::create(["line" => "3350", "itinerary" => "IGARAPÉ/VIA RESPLENDOR/VIA MAGNA SEATING/BETIM"]);
        Bus::create(["line" => "3351", "itinerary" => "IGARAPÉ/BETM"]);
        Bus::create(["line" => "3352", "itinerary" => "SÃO JOAQUIM DE BICAS/VILA RICA VIA MAGNA SEATING/BETIM"]);
        Bus::create(["line" => "3353", "itinerary" => "3353 - SÃO J. DE BICAS/V.RICA/V.MAGNA SEATING/P.BRANCA/BETIM"]);
        Bus::create(["line" => "3355", "itinerary" => "CANAA/VILA NUNES/BELO HORIZONTE"]);
        Bus::create(["line" => "3356", "itinerary" => "CANAÃ/VILA NUNES VIA AV. SÃO PAULO/BH"]);
        Bus::create(["line" => "3365", "itinerary" => "CANAA/JACANA/BELO HORIZONTE"]);
        Bus::create(["line" => "3370", "itinerary" => "CANAA/CANOAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3380", "itinerary" => "CANAA/SAO PEDRO/BELO HORIZONTE"]);
        Bus::create(["line" => "3390", "itinerary" => "JARDIM DAS ROSAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3400", "itinerary" => "BAIRRO VARZEA/BELO HORIZONTE"]);
        Bus::create(["line" => "3410", "itinerary" => "IBIRITE VIA RUA ALTIVAS CALDAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3420", "itinerary" => "IBIRITE VIA VARZEA/BELO HORIZONTE"]);
        Bus::create(["line" => "3430", "itinerary" => "MONSENHOR HORTA VIA PARQUE ESTRELA DO SUL/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3440", "itinerary" => "JARDIM MONTANHES/BELO HORIZONTE"]);
        Bus::create(["line" => "3450", "itinerary" => "BOSQUE DE IBIRITE/BELO HORIZONTE"]);
        Bus::create(["line" => "3460", "itinerary" => "BAIRRO MONSENHOR HORTA/ESTACAO ELDORADO - INTEGRADO"]);
        Bus::create(["line" => "3470", "itinerary" => "NOSSA SENHORA DE FATIMA - VISTA ALEGRE/BELO HORIZONTE"]);
        Bus::create(["line" => "3480", "itinerary" => "NOSSA SENHORA FATIMA/BELO HORIZONTE"]);
        Bus::create(["line" => "3490", "itinerary" => "LAGO AZUL VIA JARDIM DAS ROSAS/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3500", "itinerary" => "IBIRITE/BELO HORIZONTE"]);
        Bus::create(["line" => "3501", "itinerary" => "IBIRITÉ/BELO HORIZONTE (SERVIÇO EXECUTIVO)"]);
        Bus::create(["line" => "3510", "itinerary" => "BAIRRO CENTRAL PARK /ESTACAO ELDORADO"]);
        Bus::create(["line" => "3520", "itinerary" => "NOSSA SENHORA FATIMA/IBIRITE/BELO HORIZONTE"]);
        Bus::create(["line" => "3530", "itinerary" => "BOSQUE IBIRITE/ESTACAO DIAMANTE"]);
        Bus::create(["line" => "3540", "itinerary" => "BAIRRO ELDORADO/ESTACAO ELDORADO VIA IBIRITE"]);
        Bus::create(["line" => "3550", "itinerary" => "RECANTO VERDE/JARDIM DAS FLORES/BELO HORIZONTE"]);
        Bus::create(["line" => "3560", "itinerary" => "MARILANDIA/BELO HORIZONTE"]);
        Bus::create(["line" => "3570", "itinerary" => "ITAIPU/ESTACAO DIAMANTE "]);
        Bus::create(["line" => "3650", "itinerary" => "BRASILIA/SARZEDO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3660", "itinerary" => "SARZEDO/BAIRRO BRASILIA VIA AV. SANTO ANTONIO/CID.INDUSTRIAL"]);
        Bus::create(["line" => "3670", "itinerary" => "SARZEDO/CARREFOUR/MAKRO"]);
        Bus::create(["line" => "3680", "itinerary" => "BRASILIA/SARZEDO - IMACULADA CONCEICAO"]);
        Bus::create(["line" => "3690", "itinerary" => "SARZEDO/IMACULADA CONCEICAO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3700", "itinerary" => "BAIRRO BANDEIRINHAS/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3710", "itinerary" => "ANCHIETA/SAO JOAQUIM/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3720", "itinerary" => "MARIO CAMPOS VIA FUNIL/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3730", "itinerary" => "MARIO CAMPOS VIA AV. MAGALHAES PINTO/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3731", "itinerary" => "INSTITUTO CULTURAL INHOTIM/BELO HORIZONTE"]);
        Bus::create(["line" => "3732", "itinerary" => "INSTITUTO CULTURAL INHOTIM/BELO HORIZONTE - EXECUTIVO"]);
        Bus::create(["line" => "3740", "itinerary" => "MARIO CAMPOS VIA TANGARA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3750", "itinerary" => "SARZEDO/BETIM"]);
        Bus::create(["line" => "3760", "itinerary" => "SANTA ROSA - RIACHO DA MATA/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3770", "itinerary" => "SARZEDO/BETIM VIA CENTRO"]);
        Bus::create(["line" => "3780", "itinerary" => "RESIDENCIAL MASTERVILLE/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3782", "itinerary" => "MARIO CAMPOS/BELO HORIZONTE"]);
        Bus::create(["line" => "3783", "itinerary" => "BRUMADINHO VIA BR 381/BELO HORIZONTE"]);
        Bus::create(["line" => "3787", "itinerary" => "CONCEIÇÃO ITAGUÁ/BELO HORIZONTE"]);
        Bus::create(["line" => "3788", "itinerary" => "BRUMADINHO/BELO HORIZONTE"]);
        Bus::create(["line" => "3789", "itinerary" => "BRUMADINHO/BETIM VIA SARZEDO"]);
        Bus::create(["line" => "3792", "itinerary" => "RIO MANSO/BELO HORIZONTE"]);
        Bus::create(["line" => "3793", "itinerary" => "RIO MANSO/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "3797", "itinerary" => "RIO MANSO/VIA BRUMADINHO/BELO HORIZONTE"]);
        Bus::create(["line" => "3798", "itinerary" => "BRUMADINHO/IGARAPÉ/BRUMADINHO"]);
        Bus::create(["line" => "3802", "itinerary" => "ITATIAIUÇÚ/BELO HORIZONTE"]);
        Bus::create(["line" => "3803", "itinerary" => "ITATIAIUÇU/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "3827", "itinerary" => "NOVA LIMA/CIDADE INDUSTRIAL VIA CEFET"]);
        Bus::create(["line" => "3828", "itinerary" => "NOVA LIMA/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3829", "itinerary" => "RAPOSOS / NOVA LIMA / CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "3831", "itinerary" => "NOVA LIMA / BELO HORIZONTE"]);
        Bus::create(["line" => "3832", "itinerary" => "NOVA LIMA/BELO HORIZONTE"]);
        Bus::create(["line" => "3833", "itinerary" => "NOVA LIMA  AV. BERNARDO DE BARROS/BELO HORIZONTE"]);
        Bus::create(["line" => "3834", "itinerary" => "CONDOMÍNIO VILLA MONTE VERDE/BELO HORIZONTE"]);
        Bus::create(["line" => "3837", "itinerary" => "HONÓRIO BICALHO/BELO HORIZONTE"]);
        Bus::create(["line" => "3838", "itinerary" => "RIO ACIMA/BELO HORIZONTE"]);
        Bus::create(["line" => "3842", "itinerary" => "RAPOSOS/BELO HORIZONTE"]);
        Bus::create(["line" => "3843", "itinerary" => "RETORNO EXPRESSO RAPOSOS/BH SHOPPING"]);
        Bus::create(["line" => "3847", "itinerary" => "RAPOSOS/NOVA LIMA"]);
        Bus::create(["line" => "3848", "itinerary" => "RIO ACIMA/NOVA LIMA"]);
        Bus::create(["line" => "3850", "itinerary" => "CITROLANDIA/BELO HORIZONTE"]);
        Bus::create(["line" => "3851", "itinerary" => "SÃO JOAQUIM DE BICAS / BH"]);
        Bus::create(["line" => "3852", "itinerary" => "RAPOSOS/NOVA LIMA-ATEND. CIRCULAR"]);
        Bus::create(["line" => "3855", "itinerary" => "CITROLANDIA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3860", "itinerary" => "BAIRRO PAQUETA/BELO HORIZONTE"]);
        Bus::create(["line" => "3865", "itinerary" => "CITROLANDIA  VIA RUA GERALDO JOSE VIEIRA/BELO HORIZONTE"]);
        Bus::create(["line" => "3870", "itinerary" => "CITROLANDIA  VIA SAO JORGE/CARREFOUR"]);
        Bus::create(["line" => "3900", "itinerary" => "CONDOMINIO RETIRO DAS PEDRAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3901", "itinerary" => "RETIRO DAS PEDRAS/ESTAÇÃO ELDORADO VIA JARDIM CANADÁ"]);
        Bus::create(["line" => "3905", "itinerary" => "JARDIM CANADA/BELO HORIZONTE"]);
        Bus::create(["line" => "3910", "itinerary" => "JARDIM CANADA II/BELO HORIZONTE"]);
        Bus::create(["line" => "3911", "itinerary" => "JARDIM CANADA II/BH SHOPPING VIA COND. RETIRO DAS PEDRAS"]);
        Bus::create(["line" => "3915", "itinerary" => "SAO SEBASTIAO DAS AGUAS CLARAS/BELO HORIZONTE"]);
        Bus::create(["line" => "3932", "itinerary" => "CASA BRANCA/BELO HORIZONTE "]);
        Bus::create(["line" => "3933", "itinerary" => "MORRO DO CHAPEU/BELO HORIZONTE"]);
        Bus::create(["line" => "3937", "itinerary" => "CAMPINHO VIA CÓRREGO FERREIRA/RETIRO DO CHALÉ"]);
        Bus::create(["line" => "3938", "itinerary" => "CONDOMINIO PASSÁRGADA/BELO HORIZONTE"]);
        Bus::create(["line" => "3942", "itinerary" => "CASA BRANCA VIA SERRA DO ROLA MOÇA/BELO HORIZONTE"]);
        Bus::create(["line" => "3943", "itinerary" => "SUZANA/BELO HORIZONTE"]);
        Bus::create(["line" => "3947", "itinerary" => "CONDOMINIO ALPHAVILLE/BELO HORIZONTE"]);
        Bus::create(["line" => "3950", "itinerary" => "JUATUBA/AZURITA"]);
        Bus::create(["line" => "3953", "itinerary" => "FLORESTAL / ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "3954", "itinerary" => "FLORESTAL / JUATUBA"]);
        Bus::create(["line" => "3955", "itinerary" => "SITIO NOVO/JUATUBA"]);
        Bus::create(["line" => "3956", "itinerary" => "AZURITA/MATEUS LEME/JUATUBA/BELO HORIZONTE"]);
        Bus::create(["line" => "3957", "itinerary" => "MATEUS LEME/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3958", "itinerary" => "AZURITA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3962", "itinerary" => "AZURITA VIA SAMAMBAIA/ESTACAO ELDORADO "]);
        Bus::create(["line" => "3963", "itinerary" => "AZURITA VIA MATEUS LEME/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3967", "itinerary" => "MATEUS LEME/BETIM"]);
        Bus::create(["line" => "3968", "itinerary" => "JUATUBA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "3975", "itinerary" => "IGARAPE/SAO JOAQUIM DE BICAS"]);
        Bus::create(["line" => "3980", "itinerary" => "IGARAPE/NOSSA SENHORA DA PAZ"]);
        Bus::create(["line" => "3985", "itinerary" => "IGARAPE/NOSSA SENHORA DA PAZ VIA SAO JOAQUIM DE BICAS"]);
        Bus::create(["line" => "3992", "itinerary" => "ITAGUARA/BELO HORIZONTE "]);
        Bus::create(["line" => "3993", "itinerary" => "ITAGUARA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "400C", "itinerary" => "TERMINAL SÃO GABRIEL/BH - DIRETA"]);
        Bus::create(["line" => "401C", "itinerary" => "TERMINAL SÃO GABRIEL/BH - PARADORA"]);
        Bus::create(["line" => "4020", "itinerary" => "TERMINAL SANTA LUZIA/ESTAÇÃO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "4025", "itinerary" => "TERMINAL SÃO BENEDITO/ESTAÇÃO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "4030", "itinerary" => "TERMINAL SAO BENEDITO/ALAMEDA DA SERRA VIA ANEL RODOVIARIO"]);
        Bus::create(["line" => "405R", "itinerary" => "TERMINAL SÃO GABRIEL/CID. INDUSTRIAL - VIA EXPRESSA"]);
        Bus::create(["line" => "406R", "itinerary" => "TERMINAL SÃO GABRIEL/CID. INDUSTRIAL - VIA AMAZONAS"]);
        Bus::create(["line" => "4100", "itinerary" => "SANTA LUZIA VIA KENNEDY/BELO HORIZONTE"]);
        Bus::create(["line" => "4105", "itinerary" => "SANTA LUZIA VIA INDUSTRIAL AMERICANO/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4110", "itinerary" => "SANTA LUZIA VIA BONANZA/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4115", "itinerary" => "MARIA ADELIA VIA BICAS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4120", "itinerary" => "SANTA LUZIA VIA VILA OLGA/BELO HORIZONTE "]);
        Bus::create(["line" => "4125", "itinerary" => "TAQUARACU DE BAIXO/BELO HORIZONTE"]);
        Bus::create(["line" => "4126", "itinerary" => "BELO HORIZONTE/TAQUARAÇU DE MINAS VIA SANTA LUZIA"]);
        Bus::create(["line" => "4127", "itinerary" => "SANTA LUZIA/TAQUARAÇU DE MINAS"]);
        Bus::create(["line" => "4130", "itinerary" => "CORREGO DAS CALCADAS VIA BR-262/BELO HORIZONTE"]);
        Bus::create(["line" => "4135", "itinerary" => "PINHOES/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4140", "itinerary" => "FRIMISA/BELO HORIZONTE"]);
        Bus::create(["line" => "4145", "itinerary" => "FRIMISA VIA VILA OLGA/TERMINAL SAO GABRIEL "]);
        Bus::create(["line" => "4150", "itinerary" => "ESTACAO SAO GABRIEL/TUNEL LAGOINHA VIA AV.CRISTIANO MACHADO"]);
        Bus::create(["line" => "4155", "itinerary" => "BAIRRO IMPERIAL/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4156", "itinerary" => "MORADA DO RIO /TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4160", "itinerary" => "BAIRRO IMPERIAL/ESTACAO SAO GABRIEL "]);
        Bus::create(["line" => "4165", "itinerary" => "PADRE MIGUEL-ROSARINHA VIA SANTA RITA/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4170", "itinerary" => "RUA MARIA AUGUSTA DOS REIS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4175", "itinerary" => "VALE DAS ACACIAS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4180", "itinerary" => "PADRE MIGUEL-ROSARINHA VIA SANTA RITA/ESTACAO SAO GABRIEL"]);
        Bus::create(["line" => "4185", "itinerary" => "BARREIRO DO AMARAL/TERMINAL SAO GABRIEL"]);
        Bus::create(["line" => "4190", "itinerary" => "SANTA LUZIA VIA INDUSTRIAL AMERICANO/ESTACAO SAO GABRIEL "]);
        Bus::create(["line" => "4195", "itinerary" => "SAO BENEDITO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "4200", "itinerary" => "CONJUNTO CRISTINA/BELO HORIZONTE"]);
        Bus::create(["line" => "4205", "itinerary" => "CONJUNTO CRISTINA/BELO HORIZONTE - BAIRRO SAO CRISTOVAO"]);
        Bus::create(["line" => "4210", "itinerary" => "CONJUNTO CRISTINA/B.HTE. - AVENIDA BRASILIA  "]);
        Bus::create(["line" => "4215", "itinerary" => "CONJUNTO CRISTINA/BELO HORIZONTE - AVENIDA PARANA - EXPRESSO"]);
        Bus::create(["line" => "4220", "itinerary" => "SAO COSME/BELO HORIZONTE VIA AV. ANTONIO CARLOS"]);
        Bus::create(["line" => "4225", "itinerary" => "BAIRRO TRES CORACOES/BELO HORIZONTE VIA AV. ANTONIO CARLOS"]);
        Bus::create(["line" => "4230", "itinerary" => "CONJUNTO CRISTINA B/BELO HORIZONTE"]);
        Bus::create(["line" => "4235", "itinerary" => "CONJUNTO CRISTINA C/BELO HORIZONTE (SERVICO ALIMENTADOR)"]);
        Bus::create(["line" => "4240", "itinerary" => "NOVA CONQUISTA/BELO HORIZONTE"]);
        Bus::create(["line" => "4245", "itinerary" => "BELO VALE/BELO HORIZONTE VIA ANTONIO CARLOS"]);
        Bus::create(["line" => "4250", "itinerary" => "SAO BENEDITO VIA COLEGIO/BELO HORIZONTE"]);
        Bus::create(["line" => "4255", "itinerary" => "SAO BENEDITO VIA SAO JOSE/BELO HORIZONTE"]);
        Bus::create(["line" => "4260", "itinerary" => "DUQUESA II VIA MONTE CARLO/BELO HORIZONTE"]);
        Bus::create(["line" => "4265", "itinerary" => "SAO BENEDITO VIA COLEGIO/BELO HORIZONTE VIA CANAA"]);
        Bus::create(["line" => "4270", "itinerary" => "SAO BENEDITO VIA SAO JOSE/BELO HORIZONTE VIA ANTONIO CARLOS"]);
        Bus::create(["line" => "4275", "itinerary" => "CANAA/BELO HORIZONTE"]);
        Bus::create(["line" => "4280", "itinerary" => "BAIRRO  LONDRINA/BELO HORIZONTE"]);
        Bus::create(["line" => "4285", "itinerary" => "BARONESA/BELO HORIZONTE"]);
        Bus::create(["line" => "4290", "itinerary" => "BARONESA/VENDA NOVA (SERVICO ALIMENTADOR)"]);
        Bus::create(["line" => "4295", "itinerary" => "AVENIDA ASIA/BELO HORIZONTE VIA ANTONIO CARLOS"]);
        Bus::create(["line" => "4300", "itinerary" => "LUXEMBURGO/BELO HORIZONTE"]);
        Bus::create(["line" => "4305", "itinerary" => "BAIRRO ASTECA/BELO HORIZONTE"]);
        Bus::create(["line" => "4310", "itinerary" => "SANTA LUZIA - PRACA CARMEM MIRANDA/BELO HORIZONTE"]);
        Bus::create(["line" => "4315", "itinerary" => "PALMITAL A/BELO HORIZONTE"]);
        Bus::create(["line" => "4320", "itinerary" => "SANTA LUZIA - PRACA SAVASSI/BELO HORIZONTE"]);
        Bus::create(["line" => "4325", "itinerary" => "BAIRRO TRES CORACOES/BELO HORIZONTE VIA CRISTIANO MACHADO "]);
        Bus::create(["line" => "4330", "itinerary" => "PALMITAL/VILARINHO/VENDA NOVA (SERVICO ALIMENTADOR)"]);
        Bus::create(["line" => "4335", "itinerary" => "PALMITAL B/BELO HORIZONTE"]);
        Bus::create(["line" => "4340", "itinerary" => "BARONESA/LONDRINA/BELO HORIZONTE"]);
        Bus::create(["line" => "4345", "itinerary" => "AVENIDA ASIA/BELO HORIZONTE VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "4350", "itinerary" => "PALMITAL VIA SAO COSME/BELO HORIZONTE (SERVICO ALIMENTADOR)"]);
        Bus::create(["line" => "4355", "itinerary" => "ALTO SAO COSME/BELO HORIZONTE"]);
        Bus::create(["line" => "4360", "itinerary" => "SAO BENEDITO/BELO HORIZONTE"]);
        Bus::create(["line" => "4365", "itinerary" => "SAO BENEDITO/B.HTE. - COLEGIO SAO JOSE (SERVICO ALIMENTADOR)"]);
        Bus::create(["line" => "4370", "itinerary" => "DUQUESA II/BELO HORIZONTE (SERVICO ALIMENTADOR)"]);
        Bus::create(["line" => "4375", "itinerary" => "BELO VALE/BELO HORIZONTE (SERVICO ALIMENTADOR)"]);
        Bus::create(["line" => "4380", "itinerary" => "BAIRRO BOM DESTINO/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4381", "itinerary" => "BOM DESTINO 2ª SEÇÃO /TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4385", "itinerary" => "BOM DESTINO/ESTACAO SAO GABRIEL "]);
        Bus::create(["line" => "4390", "itinerary" => "CORREGO DAS CALCADAS/B.HTE. VIA AVENIDA ANTONIO CARLOS"]);
        Bus::create(["line" => "4395", "itinerary" => "PALMITAL/VENDA NOVA"]);
        Bus::create(["line" => "4400", "itinerary" => "RESIDENCIAL DA MATA/BAMBUZAL/BELO HORIZONTE"]);
        Bus::create(["line" => "4405", "itinerary" => "SAO COSME/BELO HORIZONTE VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "4410", "itinerary" => "SAO BENEDITO/BELO HORIZONTE  VIA AVENIDA BRASILIA"]);
        Bus::create(["line" => "4415", "itinerary" => "BAIRRO TRES CORACOES/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "4420", "itinerary" => "BARONESA/RES.DA MATA/BAMBUZAL/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "4425", "itinerary" => "SAO BENEDITO/CIDADE INDUSTRIAL  VIA ANEL RODOVIARIO"]);
        Bus::create(["line" => "4435", "itinerary" => "SANTA LUZIA/BELO HORIZONTE VIA PRACA GETÚLIO VARGAS"]);
        Bus::create(["line" => "4440", "itinerary" => "TAQUARAÇU/SANTA LUZIA"]);
        Bus::create(["line" => "4442", "itinerary" => "TAQUARAÇU DE MINAS/TERMINAL SÃO GABRIEL "]);
        Bus::create(["line" => "4445", "itinerary" => "CORREGO DAS CALÇADAS VIA BR-381/TERMINAL SAO GABRIEL "]);
        Bus::create(["line" => "4450", "itinerary" => "SANTA LUZIA/TERMINAL SÃO GABRIEL - EXECUTIVO"]);
        Bus::create(["line" => "4600", "itinerary" => "BORDA DA MATA/NOSSA SENHORA DE FATIMA/BELO HORIZONTE"]);
        Bus::create(["line" => "4605", "itinerary" => "VILA SAO JOSE/BELO HORIZONTE"]);
        Bus::create(["line" => "4610", "itinerary" => "COQUEIROS/ITACOLOMI/BELO HORIZONTE"]);
        Bus::create(["line" => "4615", "itinerary" => "TERMINAL ANA LÚCIA/BAIRRO ALVORADA/BELO HORIZONTE"]);
        Bus::create(["line" => "4620", "itinerary" => "TERMINAL ANA LÚCIA/ BAIRRO NOVO ALVORADA/BELO HORIZONTE"]);
        Bus::create(["line" => "4625", "itinerary" => "TERMINAL ANA LÚCIA/ALVORADA DE CIMA/BELO HORIZONTE"]);
        Bus::create(["line" => "4630", "itinerary" => "SERVICO AUXILIAR GENERAL CARNEIRO"]);
        Bus::create(["line" => "4635", "itinerary" => "BAIRRO CAMPOS ELISEOS/BELO HORIZONTE"]);
        Bus::create(["line" => "4640", "itinerary" => "VILA ALTO BONITO/BELO HORIZONTE"]);
        Bus::create(["line" => "4645", "itinerary" => "BELO HORIZONTE/GENERAL CARNEIRO VIA CARVALHO DE BRITO"]);
        Bus::create(["line" => "4650", "itinerary" => "GENERAL CARNEIRO - PRACA CENTRAL/BELO HORIZONTE"]);
        Bus::create(["line" => "4651", "itinerary" => "GENERAL CARNEIRO-PRAÇA CENTRAL/RUA SANTA CATARINA/BH"]);
        Bus::create(["line" => "4655", "itinerary" => "NOSSA SENHORA DE FÁTIMA/CARMO DA MATA/BH"]);
        Bus::create(["line" => "4660", "itinerary" => "GENERAL CARNEIRO/RUA UBERLANDIA/BH"]);
        Bus::create(["line" => "4665", "itinerary" => "GENERAL CARNEIRO/BELO HORIZONTE"]);
        Bus::create(["line" => "4670", "itinerary" => "NACOES UNIDAS/BELO HORIZONTE"]);
        Bus::create(["line" => "4675", "itinerary" => "NOSSA SENHORA DE FATIMA/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4676", "itinerary" => "NOSSA SENHORA DE FÁTIMA/CARVALHO DE BRITO/BH"]);
        Bus::create(["line" => "4677", "itinerary" => "BAIRRO NAÇÕES UNIDAS/BH VIA AV. CRISTIANO MACHADO"]);
        Bus::create(["line" => "4680", "itinerary" => "NOSSA SENHORA DE FATIMA-MANGUEIRAS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4685", "itinerary" => "NOSSA SENHORA DE FATIMA-EUCALIPTOS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4686", "itinerary" => "CARMO DA MATA/EUCALIPTOS/BELO HORIZONTE"]);
        Bus::create(["line" => "4690", "itinerary" => "NOSSA SENHORA DE FATIMA/ESTACAO SAO GABRIEL"]);
        Bus::create(["line" => "4695", "itinerary" => "NOSSA SENHORA DE FATIMA/CAPITAO EDUARDO"]);
        Bus::create(["line" => "4800", "itinerary" => "CAETE/TERMINAL SÃO GABRIEL-EXECUTIVO"]);
        Bus::create(["line" => "4810", "itinerary" => "CAETÉ/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4820", "itinerary" => "CAETÉ VIA JOSÉ BRANDÃO/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4830", "itinerary" => "CAETE VIA CIDADE INDUSTRIAL/CONTAGEM"]);
        Bus::create(["line" => "4872", "itinerary" => "RAVENA/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4879", "itinerary" => "CARMO UNIÃO/CAETÉ"]);
        Bus::create(["line" => "4880", "itinerary" => "CAETÉ/NOVA UNIÃO"]);
        Bus::create(["line" => "4881", "itinerary" => "NOVA UNIÃO/CAETÉ VIA ANTONIO DOS SANTOS"]);
        Bus::create(["line" => "4882", "itinerary" => "NOVA UNIÃO/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4883", "itinerary" => "ROÇAS NOVAS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4887", "itinerary" => "ANTÔNIO DOS SANTOS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4900", "itinerary" => "BORBA GATO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "4905", "itinerary" => "ALAMEDA DA SERRA/CIDADE INDUSTRIAL RETORNO AV. CATALAO"]);
        Bus::create(["line" => "4910", "itinerary" => "VITORIA VIA GORDURAS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4915", "itinerary" => "JARDIM VITORIA/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4916", "itinerary" => "VILA MARIA/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4920", "itinerary" => "BORBA GATO/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "4925", "itinerary" => "VILA BARRAGINHA VIA CIDADE INUSTRIAL/ALAMEDA DA SERRA"]);
        Bus::create(["line" => "4930", "itinerary" => "BAIRRO SÃO PAULO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "4970", "itinerary" => "CAETÉ/SABARÁ "]);
        Bus::create(["line" => "4986", "itinerary" => "SABARÁ/BELO HORIZONTE"]);
        Bus::create(["line" => "4987", "itinerary" => "SABARA / BELO HORIZONTE"]);
        Bus::create(["line" => "4988", "itinerary" => "SABARA/BELO HORIZONTE"]);
        Bus::create(["line" => "4989", "itinerary" => "SABARÁ/RETORNO AV. JOSÉ CÂNDIDO DA SILVEIRA"]);
        Bus::create(["line" => "4992", "itinerary" => "SABARA VIA BARRAGINHA/BELO HORIZONTE"]);
        Bus::create(["line" => "4993", "itinerary" => "ROCAS GRANDES/BELO HORIZONTE"]);
        Bus::create(["line" => "4997", "itinerary" => "BAIRRO ROSARIO/BELO HORIZONTE"]);
        Bus::create(["line" => "4998", "itinerary" => "RESIDENCIAL MANGUEIRAS/BELO HORIZONTE"]);
        Bus::create(["line" => "5000", "itinerary" => "SAO JOSE DA LAPA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5020", "itinerary" => "JUSTINOPOLIS/ALAMEDA DA SERRA VIA ANEL RODOVIARIO"]);
        Bus::create(["line" => "5030", "itinerary" => "NOVA PAMPULHA 3a. E 4a. SECOES/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5045", "itinerary" => "SERRA DOURADA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5055", "itinerary" => "TERMINAL MORRO ALTO/ALAMEDA DA SERRA VIA ANEL RODOVIARIO"]);
        Bus::create(["line" => "5070", "itinerary" => "BAIRRO CELVIA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5075", "itinerary" => "CONJUNTO CAIEIRAS/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5100", "itinerary" => "LAGOA SANTA/PEDRO LEOPOLDO VIA FIDALGO"]);
        Bus::create(["line" => "5110", "itinerary" => "DR. LUND/LAGOA SANTA VIA CONFINS"]);
        Bus::create(["line" => "5111", "itinerary" => "AEROPORTO INTERNACIONAL TANCREDO NEVES / LAGOA SANTA"]);
        Bus::create(["line" => "5112", "itinerary" => "CIDADE DE CONFINS / LAGOA SANTA"]);
        Bus::create(["line" => "5119", "itinerary" => "PEDRO LEOPOLDO/AEROPORTO T. NEVES VIA LAPA VERM.V TAVARES"]);
        Bus::create(["line" => "512H", "itinerary" => "TERMINAL VILARINHO/HOSPITAIS"]);
        Bus::create(["line" => "5120", "itinerary" => "AER.TANCREDO NEVES/PEDRO LEOPOLDO VIA DR. LUND"]);
        Bus::create(["line" => "5130", "itinerary" => "SAO JOSE DA LAPA VIA DOM PEDRO I /BELO HORIZONTE"]);
        Bus::create(["line" => "5140", "itinerary" => "SAO JOSE DA LAPA/BELO HORIZONTE"]);
        Bus::create(["line" => "5150", "itinerary" => "SAO JOSE DA LAPA/BELO HORIZONTE - INACIA DE CARVALHO"]);
        Bus::create(["line" => "5160", "itinerary" => "SAO JOSE DA LAPA/BELO HORIZONTE VIA CACHOEIRA"]);
        Bus::create(["line" => "5161", "itinerary" => "SÃO JOSÉ DA LAPA / BH / CACHOEIRA VIA LAR DE MINAS"]);
        Bus::create(["line" => "5170", "itinerary" => "CACHOEIRA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5180", "itinerary" => "PEDRO LEOPOLDO/QUINTA DO SUMIDOURO"]);
        Bus::create(["line" => "5190", "itinerary" => "PEDRO LEOPOLDO/PALMITAL"]);
        Bus::create(["line" => "5200", "itinerary" => "PEDRO LEOPOLDO/QUINTA DAS PALMEIRAS"]);
        Bus::create(["line" => "5210", "itinerary" => "SAO JOSE DA LAPA/BELO HORIZONTE VIA LAR DE MINAS"]);
        Bus::create(["line" => "5220", "itinerary" => "BELO HORIZONTE/AEC - ASSOCIACAO DOS EMPREGADOS DO COMERCIO"]);
        Bus::create(["line" => "5230", "itinerary" => "LAR DE MINAS/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5240", "itinerary" => "AER.TANCREDO NEVES VIA ANTONIO CARLOS/B. HTE - (EXECUTIVO)"]);
        Bus::create(["line" => "5250", "itinerary" => "AER.TANCREDO NEVES VIA ANTONIO CARLOS/BH - (CONVENCIONAL)"]);
        Bus::create(["line" => "5251", "itinerary" => "AER. INTER. TANCREDO NEVES/AER.CARLOS DRUMOND DE ANDRADE"]);
        Bus::create(["line" => "5252", "itinerary" => "AER.INT.TAN.NEVES/TER.GOV.ISRAEL PINHEIRO VIA AV. ANT.CARLOS"]);
        Bus::create(["line" => "5260", "itinerary" => "AEROPORTO INTERNACIONAL TANCREDO NEVES / BELO HORIZONTE"]);
        Bus::create(["line" => "5270", "itinerary" => "AEROPORTO INTERNACIONAL TANCREDO NEVES / BELO HORIZONTE"]);
        Bus::create(["line" => "5271", "itinerary" => "AER.INTER.TANCREDO NEVES/BH-VIA AV. CRISTIANO MACHADO"]);
        Bus::create(["line" => "5278", "itinerary" => "CIDADE DE CONFINS/AEROPORTO  INTER. TANCREDO NEVES"]);
        Bus::create(["line" => "5279", "itinerary" => "VESPASIANO/CIDADE DE CONFINS"]);
        Bus::create(["line" => "5280", "itinerary" => "VESPASIANO/AEROPORTO INTERNACIONAL TANCREDO NEVES"]);
        Bus::create(["line" => "5282", "itinerary" => "MOCAMBEIRO/BELO HORIZONTE - VIA ANTONIO CARLOS"]);
        Bus::create(["line" => "5283", "itinerary" => "MOCAMBEIRO/BH VIA AV.CRISTIANO MACHADO"]);
        Bus::create(["line" => "5284", "itinerary" => "SÃO JOSE DA LAPA VIA DOM PEDRO I / PEDRO LEOPOLDO"]);
        Bus::create(["line" => "5285", "itinerary" => "THEOTÔNIO BATISTA DE FREITAS/ESTAÇÃO VILARINHO"]);
        Bus::create(["line" => "5286", "itinerary" => "MOCAMBEIRO/AEROPORTO INTERNACIONAL TANCREDO NEVES"]);
        Bus::create(["line" => "5287", "itinerary" => "MOCAMBEIRO/PEDRO LEOPOLDO VIA ADÉLIA ISSA"]);
        Bus::create(["line" => "5288", "itinerary" => "MOCAMBEIRO/PEDRO LEOPOLDO/DOM CAMILO"]);
        Bus::create(["line" => "5292", "itinerary" => "MOCAMBEIRO/SÃO JOSÉ DA LAPA"]);
        Bus::create(["line" => "5293", "itinerary" => "LAGOA SANTO ANTONIO VIA THEOTONIO BATISTA DE FREITAS/BH"]);
        Bus::create(["line" => "5294", "itinerary" => "PEDRO LEOPOLDO/BELO HORIZONTE"]);
        Bus::create(["line" => "5295", "itinerary" => "PEDRO LEOPOLDO/BELO HORIZONTE VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5296", "itinerary" => "PEDRO LEOPOLDO/TREVO SÃO JOSÉ DA LAPA"]);
        Bus::create(["line" => "5297", "itinerary" => "PEDRO LEOPOLDO/BELO HORIZONTE VIA AV. ANTONIO CARLOS"]);
        Bus::create(["line" => "5298", "itinerary" => "CONFINS/BELO HORIZONTE VIA AV. ANTÔNIO CARLOS"]);
        Bus::create(["line" => "5299", "itinerary" => "P. LEOPOLDO/AER.INT.TAN.NEVES/AER.PAMPULHA/BH VIA ANT.CARLOS"]);
        Bus::create(["line" => "5300", "itinerary" => "P. LEOPOLDO/AER. INT. TANC. NEVES/BH VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5302", "itinerary" => "CONFINS VIA AEROPORTO/BELO HORIZONTE "]);
        Bus::create(["line" => "5303", "itinerary" => "CONFINS/SÃO JOSÉ DA LAPA"]);
        Bus::create(["line" => "5304", "itinerary" => "CACHOEIRA/TREVO LAGOA SANTA"]);
        Bus::create(["line" => "5305", "itinerary" => "PEDRO LEOPOLDO/BELO HORIZONTE VIA AV. ANTÔNIO CARLOS"]);
        Bus::create(["line" => "5306", "itinerary" => "PEDRO LEOPOLDO/BELO HTE - MG424 VIA AV. CRISTIANO MACHADO"]);
        Bus::create(["line" => "5307", "itinerary" => "PEDRO LEOPOLDO/BELO HORIZONTE VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5308", "itinerary" => "ATENDIMENTO DOM PEDRO I VIA  CRISTIANO MACHADO/BELO HTE "]);
        Bus::create(["line" => "5309", "itinerary" => "P.LEOPOLDO/AER.INT.TAN.NEVES/AER.PAMPULHA/BH VIA ANT.CARLOS"]);
        Bus::create(["line" => "5310", "itinerary" => "PEDRO LEOPOLDO/AER. INT.TANC.NEVES/BH VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5311", "itinerary" => "CONFINS/AER.INTER.TANC.NEVES/BH VIA AV. CRISTIANO MACHADO"]);
        Bus::create(["line" => "5350", "itinerary" => "BELO HORIZONTE/AREIAS"]);
        Bus::create(["line" => "5355", "itinerary" => "BELO HORIZONTE/AREIAS VIA INACIA DE CARVALHO"]);
        Bus::create(["line" => "5356", "itinerary" => "BELO HORIZONTE/JABOTICATUBAS VIA LAGOA SANTA"]);
        Bus::create(["line" => "5357", "itinerary" => "BELO HORIZONTE/JABOTICATUBAS VIA SANTA LUZIA"]);
        Bus::create(["line" => "5358", "itinerary" => "SANTA LUZIA/SÃO JOSÉ DE ALMEIDA"]);
        Bus::create(["line" => "5360", "itinerary" => "SUELY/BELO HORIZONTE"]);
        Bus::create(["line" => "5365", "itinerary" => "JUSTINOPOLIS/BELO HORIZONTE"]);
        Bus::create(["line" => "5370", "itinerary" => "JUSTINOPOLIS/BELO HORIZONTE VIA PRACA DA MATRIZ"]);
        Bus::create(["line" => "5375", "itinerary" => "JUSTINOPOLIS/BELO HORIZONTE VIA CRUZEIRO"]);
        Bus::create(["line" => "5376", "itinerary" => "CRUZEIRO / ESTAÇÃO VILARINHO"]);
        Bus::create(["line" => "5380", "itinerary" => "GIRASSOL/VENDA NOVA/ESTAÇÃO VILARINHO"]);
        Bus::create(["line" => "5385", "itinerary" => "BOTAFOGO/BELO HORIZONTE "]);
        Bus::create(["line" => "5390", "itinerary" => "BOTAFOGO/BELO HORIZONTE VIA FELIXLANDIA"]);
        Bus::create(["line" => "5395", "itinerary" => "BOTAFOGO/BELO HORIZONTE VIA RUA HUM"]);
        Bus::create(["line" => "5400", "itinerary" => "FORTALEZA / BELO HORIZONTE VIA ANTONIO CARLOS"]);
        Bus::create(["line" => "5405", "itinerary" => "FORTALEZA/BELO HORIZONTE"]);
        Bus::create(["line" => "5410", "itinerary" => "PARAISO DAS PIABAS/BELO HORIZONTE"]);
        Bus::create(["line" => "5411", "itinerary" => "BAIRRO GIRASSOL"]);
        Bus::create(["line" => "5415", "itinerary" => "SUELY/BELO HORIZONTE VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5420", "itinerary" => "VIENA/BELO HORIZONTE via RESIDENCIAL SANTA HELENA"]);
        Bus::create(["line" => "5425", "itinerary" => "CÉU ANIL/BELO HORIZONTE VIA HAVAÍ"]);
        Bus::create(["line" => "5430", "itinerary" => "LUAR DA PAMPULHA/BELO HORIZONTE"]);
        Bus::create(["line" => "5432", "itinerary" => "TORONTO/BELO HORIZONTE"]);
        Bus::create(["line" => "5435", "itinerary" => "BELO HORIZONTE/BAIRRO ATALAIA"]);
        Bus::create(["line" => "5440", "itinerary" => "JARDIM PRIMAVERA/BELO HORIZONTE VIA AVENIDA ANTONIO CARLOS"]);
        Bus::create(["line" => "5445", "itinerary" => "MARIA HELENA/BELO HORIZONTE"]);
        Bus::create(["line" => "5450", "itinerary" => "JARDIM PRIMAVERA/B.HTE. VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5455", "itinerary" => "JUSTINOPOLIS/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5460", "itinerary" => "INACIA DE CARVALHO/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5465", "itinerary" => "EVERESTE/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5470", "itinerary" => "SUELY/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5475", "itinerary" => "FORTALEZA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5480", "itinerary" => "MARIA HELENA 2a. SECAO/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5485", "itinerary" => "BAIRRO NOVA AMERICA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5490", "itinerary" => "JUSTINOPOLIS/BELO HORIZONTE - RETORNO EXPRESSO"]);
        Bus::create(["line" => "5495", "itinerary" => "SÃO MIGUEL/BH - VIA SANTA FÉ"]);
        Bus::create(["line" => "5500", "itinerary" => "EVERESTE/ BELO HORIZONTE VIA KÁTIA"]);
        Bus::create(["line" => "5505", "itinerary" => "VIENA/ESTAÇÃO VILARINHO /VENDA NOVA"]);
        Bus::create(["line" => "5510", "itinerary" => "TONY/BELO HORIZONTE"]);
        Bus::create(["line" => "5515", "itinerary" => "NOVA AMERICA/BELO HORIZONTE"]);
        Bus::create(["line" => "5582", "itinerary" => "JABOTICATUBAS/TERMINAL SÃO GABRIEL"]);
        Bus::create(["line" => "5600", "itinerary" => "SAO COSME/BELO HORIZONTE "]);
        Bus::create(["line" => "5605", "itinerary" => "BERNARDO DE SOUZA /B.HTE. VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5606", "itinerary" => "GÁVEA II/BELO HORIZONTE VIA AV. CRISTIANO MACHADO"]);
        Bus::create(["line" => "5610", "itinerary" => "MORRO ALTO/BELO HORIZONTE"]);
        Bus::create(["line" => "5615", "itinerary" => "JARDIM BELA VISTA/B.HTE. VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5620", "itinerary" => "NOVA PAMPULHA - BONSUCESSO/BELO HORIZONTE"]);
        Bus::create(["line" => "5625", "itinerary" => "BAIRRO SANTA CRUZ/BELO HORIZONTE"]);
        Bus::create(["line" => "5630", "itinerary" => "JARDIM BELA VISTA/BELO HORIZONTE"]);
        Bus::create(["line" => "5635", "itinerary" => "NOVA PAMPULHA 3a. E 4a. SECOES/BELO HORIZONTE"]);
        Bus::create(["line" => "5640", "itinerary" => "TOCANTINS/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5645", "itinerary" => "VIDA NOVA/FAZENDA SEVERINA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5646", "itinerary" => "VIDA NOVA1ªE2ªSEÇÃO VIA FAZ.SEVERINA/VENDANOVA/EST.VILARINHO"]);
        Bus::create(["line" => "5650", "itinerary" => "PEDRA BRANCA/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5655", "itinerary" => "LANDI/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5660", "itinerary" => "JARDIM DA GLORIA/BELO HORIZONTE"]);
        Bus::create(["line" => "5665", "itinerary" => "JARDIM DA GLORIA 2a. SECAO/BELO HORIZONTE"]);
        Bus::create(["line" => "5670", "itinerary" => "JARDIM DA GLORIA/B.HTE. VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5675", "itinerary" => "VILA ESPORTIVA/BELO HORIZONTE"]);
        Bus::create(["line" => "5680", "itinerary" => "SANTA CLARA/BELO HORIZONTE VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5685", "itinerary" => "BERNARDO DE SOUZA/BELO HORIZONTE"]);
        Bus::create(["line" => "5690", "itinerary" => "BAIRRO SANTA CLARA/BELO HORIZONTE"]);
        Bus::create(["line" => "5695", "itinerary" => "SERRA DOURADA/BELO HORIZONTE"]);
        Bus::create(["line" => "5700", "itinerary" => "PEDRA BRANCA/BELO HORIZONTE"]);
        Bus::create(["line" => "5701", "itinerary" => "TOCANTIS / BELO HORIZONTE"]);
        Bus::create(["line" => "5705", "itinerary" => "LANDI/BELO HORIZONTE"]);
        Bus::create(["line" => "5710", "itinerary" => "VIDA NOVA/FAZENDA SEVERINA/BELO HORIZONTE"]);
        Bus::create(["line" => "5711", "itinerary" => "VIDA NOVA/FAZENDA SEVERINA/BH VIA AV. CRISTIANO MACHADO"]);
        Bus::create(["line" => "5715", "itinerary" => "GAVEA II /BELO HORIZONTE VIA AVENIDA ANTONIO CARLOS"]);
        Bus::create(["line" => "5783", "itinerary" => "SÃO JOSÉ DE ALMEIDA/BELO HORIZONTE"]);
        Bus::create(["line" => "5784", "itinerary" => "BALDIM/BELO HORIZONTE"]);
        Bus::create(["line" => "5785", "itinerary" => "BALDIM/BELO HORIZONTE via VARGEM GRANDE"]);
        Bus::create(["line" => "5786", "itinerary" => "BELO HORIZONTE/BALDIM VIA FUNILÂNDIA"]);
        Bus::create(["line" => "5787", "itinerary" => "BALDIM/SÃO JOSÉ DE ALMEIDA"]);
        Bus::create(["line" => "5788", "itinerary" => "CAMPINHO/BELO HORIZONTE"]);
        Bus::create(["line" => "5789", "itinerary" => "BELO HORIZONTE/FAZENDA VARGEM DO LOBO"]);
        Bus::create(["line" => "5792", "itinerary" => "LAPINHA/BELO HORIZONTE"]);
        Bus::create(["line" => "5793", "itinerary" => "FIDALGO / BELO HORIZONTE"]);
        Bus::create(["line" => "5800", "itinerary" => "CONJUNTO CAIEIRAS/BELO HORIZONTE VIA AVENIDA ANTONIO CARLOS"]);
        Bus::create(["line" => "5805", "itinerary" => "CONJUNTO CAIEIRAS/B.HTE. VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5806", "itinerary" => "VESPASIANO/BH - SERVIÇO COMERCIAL EXECUTIVO METROPOLITANO"]);
        Bus::create(["line" => "5810", "itinerary" => "BAIRRO CELVIA/BELO HORIZONTE"]);
        Bus::create(["line" => "5815", "itinerary" => "BAIRRO CELVIA/BELO HORIZONTE VIA AVENIDA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5820", "itinerary" => "BAIRRO JANE (IMPERIAL)/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5825", "itinerary" => "BAIRRO JANE (IMPERIAL)/BELO HORIZONTE"]);
        Bus::create(["line" => "5830", "itinerary" => "VISTA ALEGRE-VALE FORMOSO/BELO HORIZONTE"]);
        Bus::create(["line" => "5835", "itinerary" => "BAIRRO NOVA YORK/BELO HORIZONTE "]);
        Bus::create(["line" => "5840", "itinerary" => "LAGOINHA/CIDADE INDUSTRIAL VIA ANEL RODOVIARIO"]);
        Bus::create(["line" => "5845", "itinerary" => "CIDADE INDUSTRIAL/LAGOINHA"]);
        Bus::create(["line" => "5850", "itinerary" => "PEDRA BRANCA/BELO HORIZONTE  VIA AVENIDA CATALAO"]);
        Bus::create(["line" => "5877", "itinerary" => "LAGOA SANTA/VESPASIANO "]);
        Bus::create(["line" => "5882", "itinerary" => "LAGOA SANTA/BELO HORIZONTE"]);
        Bus::create(["line" => "5883", "itinerary" => "AERONAUTAS/BELO HORIZONTE"]);
        Bus::create(["line" => "5884", "itinerary" => "ATEND.COMPL.LAGOA SANTA/BH VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5887", "itinerary" => "LAGOA SANTA/BH EXECUTIVO - VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5888", "itinerary" => "LAGOA SANTA/BH-EXECUTIVO VIA ANTONIO CARLOS"]);
        Bus::create(["line" => "5900", "itinerary" => "VESPASIANO/INACIA DE CARVALHO"]);
        Bus::create(["line" => "5905", "itinerary" => "TAVARES/VESPASIANO"]);
        Bus::create(["line" => "5910", "itinerary" => "VESPASIANO/SAO JOSE DA LAPA"]);
        Bus::create(["line" => "5915", "itinerary" => "VESPASIANO/SAO JOSE DA LAPA/PEDRO LEOPOLDO"]);
        Bus::create(["line" => "5920", "itinerary" => "VESPASIANO/NOVA GRANJA/CACHOEIRA "]);
        Bus::create(["line" => "5925", "itinerary" => "VESPASIANO/CACHOEIRA"]);
        Bus::create(["line" => "5930", "itinerary" => "NOVA GRANJA/CACHOEIRA"]);
        Bus::create(["line" => "5935", "itinerary" => "VESPASIANO/BAIRRO  MARAVILHA/INACIA DE CARVALHO"]);
        Bus::create(["line" => "5960", "itinerary" => "RIBEIRAO DAS NEVES/ESTACAO VILARINHO/VENDA NOVA"]);
        Bus::create(["line" => "5979", "itinerary" => "CAPIM BRANCO / AEROPORTO INTERNACIONAL TANCREDO NEVES"]);
        Bus::create(["line" => "5980", "itinerary" => "CAPIM BRANCO/MATOZINHOS"]);
        Bus::create(["line" => "5981", "itinerary" => "BAIRRO SÃO PAULO/SÃO JOSÉ/BOM JESUS/PEDRO LEOPOLDO"]);
        Bus::create(["line" => "5982", "itinerary" => "BAIRRO SÃO PAULO/VENDA NOVA"]);
        Bus::create(["line" => "5983", "itinerary" => "ARAÇÁS / PEDRO LEOPOLDO"]);
        Bus::create(["line" => "5985", "itinerary" => "BELO HORIZONTE/BOA VISTA"]);
        Bus::create(["line" => "5986", "itinerary" => "BELO HORIZONTE/CAPIM BRANCO"]);
        Bus::create(["line" => "5987", "itinerary" => "CAPIM BRANCO / PEDRO LEOPOLDO"]);
        Bus::create(["line" => "5988", "itinerary" => "BELO HORIZONTE / CAPIM BRANCO"]);
        Bus::create(["line" => "5991", "itinerary" => "BELO HORIZONTE/MATOZINHOS VIA AV. CRISTIANO MACHADO"]);
        Bus::create(["line" => "5992", "itinerary" => "BELO HORIZONTE/MATOZINHOS/VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "5993", "itinerary" => "BELO HORIZONTE / MATOZINHOS VIA ANTONIO CARLOS"]);
        Bus::create(["line" => "5997", "itinerary" => "MATOZINHOS/BELO HORIZONTE VIA BAIRROS (VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "6100", "itinerary" => "PEDRO LEOPOLDO/RIBEIRAO DAS NEVES"]);
        Bus::create(["line" => "6110", "itinerary" => "RIBEIRAO DAS NEVES/VENDA NOVA "]);
        Bus::create(["line" => "6120", "itinerary" => "RIBEIRAO DAS NEVES/CEASA VIA VENDA NOVA"]);
        Bus::create(["line" => "6121", "itinerary" => "RIBEIRÃO DAS NEVES VIA LAGOINHA/CEASA"]);
        Bus::create(["line" => "6122", "itinerary" => "RIBEIRÃO DAS NEVES/CEASA"]);
        Bus::create(["line" => "6130", "itinerary" => "SEVILHA VIA SANTA MARTINHA/BELO HORIZONTE"]);
        Bus::create(["line" => "6140", "itinerary" => "SEVILHA VIA RUA MOACIR MENEZES/BELO HORIZONTE"]);
        Bus::create(["line" => "6150", "itinerary" => "SEVILHA VIA RUA HUMBERTO PALHARES/BELO HORIZONTE"]);
        Bus::create(["line" => "6160", "itinerary" => "SEVILHA VIA RUA JOSE GERALDO GOMES/BELO HORIZONTE"]);
        Bus::create(["line" => "6170", "itinerary" => "RIBEIRAO DAS NEVES VIA ROSA NEVES/BELO HORIZONTE"]);
        Bus::create(["line" => "6171", "itinerary" => "BAIRRO MONTE VERDE/BELO HORIZONTE"]);
        Bus::create(["line" => "6180", "itinerary" => "ROSANEVES-PRACA DA CAMARA MUNICIPAL/BELO HORIZONTE"]);
        Bus::create(["line" => "6190", "itinerary" => "ROSANEVES-POSTO MEDICO/BELO HORIZONTE"]);
        Bus::create(["line" => "6200", "itinerary" => "BELO HORIZONTE/RIBEIRAO DAS NEVES"]);
        Bus::create(["line" => "6210", "itinerary" => "RIBEIRAO DAS NEVES-BAIRRO SAVASSI/BELO HORIZONTE"]);
        Bus::create(["line" => "6220", "itinerary" => "SANTINHO / SANTA MARTINHA VIA AVENIDA CRISTIANO MACHADO/BH"]);
        Bus::create(["line" => "6221", "itinerary" => "MANOEL BRANDÃO/BELO HORIZONTE VIA CRISTIANO MACHADO"]);
        Bus::create(["line" => "6230", "itinerary" => "ROSANEVES VIA AVENIDA CRISTIANO MACHADO/BELO HORIZONTE"]);
        Bus::create(["line" => "6240", "itinerary" => "SAO LUIZ/BELO HORIZONTE"]);
        Bus::create(["line" => "6250", "itinerary" => "CAMPOS SILVEIRA/BELO HORIZONTE"]);
        Bus::create(["line" => "6260", "itinerary" => "BELO HORIZONTE/VENEZA VIA BR-040"]);
        Bus::create(["line" => "6261", "itinerary" => "JARDIM VERONA/ALTEROSA/BELO HORIZONTE"]);
        Bus::create(["line" => "6270", "itinerary" => "VALE DAS ACACIAS/BELO HORIZONTE"]);
        Bus::create(["line" => "6280", "itinerary" => "BAIRRO METROPOLITANO/BELO HORIZONTE"]);
        Bus::create(["line" => "6290", "itinerary" => "CONJUNTO HENRIQUE SAPORI/BELO HORIZONTE"]);
        Bus::create(["line" => "6300", "itinerary" => "RECANTO DA MATA/BELO HORIZONTE"]);
        Bus::create(["line" => "6301", "itinerary" => "BELVEDERE/BELO HORIZONTE"]);
        Bus::create(["line" => "6310", "itinerary" => "JARDIM COLONIAL/BELO HORIZONTE "]);
        Bus::create(["line" => "6320", "itinerary" => "BAIRRO FAZENDA CASTRO/BELO HORIZONTE"]);
        Bus::create(["line" => "6330", "itinerary" => "SAN GENARO/BELO HORIZONTE"]);
        Bus::create(["line" => "6331", "itinerary" => "VALE DA PRATA/BELO HORIZONTE"]);
        Bus::create(["line" => "6340", "itinerary" => "FLORENCA/BELO HORIZONTE"]);
        Bus::create(["line" => "6350", "itinerary" => "LIBERDADE/BELO HORIZONTE"]);
        Bus::create(["line" => "6360", "itinerary" => "CIDADE NEVIANA/BELO HORIZONTE"]);
        Bus::create(["line" => "6361", "itinerary" => "COMPLEXO PRISIONAL DE NEVES/BELO HORIZONTE"]);
        Bus::create(["line" => "6370", "itinerary" => "FLORENCA VIA SAN GENARO/CEASA "]);
        Bus::create(["line" => "6380", "itinerary" => "VENEZA/CEASA/VENEZA"]);
        Bus::create(["line" => "6390", "itinerary" => "NOSSA FAZENDA/BELO HORIZONTE"]);
        Bus::create(["line" => "6391", "itinerary" => "NOSSA FAZENDA/BELO HORIZONTE"]);
        Bus::create(["line" => "6400", "itinerary" => "SAO FRANCISCO-SANTA CECILIA/BELO HORIZONTE"]);
        Bus::create(["line" => "6401", "itinerary" => "ATENDIMENTO COMPLEMENTAR SÃO FRANCISCO/BELO HORIZONTE"]);
        Bus::create(["line" => "6410", "itinerary" => "SÃO FRANCISCO VIA SANTA CECILIA/CEASA"]);
        Bus::create(["line" => "6420", "itinerary" => "BAIRRO VEREDA/BELO HORIZONTE"]);
        Bus::create(["line" => "6430", "itinerary" => "BELO HORIZONTE/VENEZA VIA AVENIDA IDA JUBELINI"]);
        Bus::create(["line" => "6440", "itinerary" => "NAPOLI VIA FRANCISCO ADRIANGELA/BELO HORIZONTE"]);
        Bus::create(["line" => "6450", "itinerary" => "FLORESTA ENCANTADA VIA SÃO PEDRO/BELO HORIZONTE"]);
        Bus::create(["line" => "6571", "itinerary" => "BAIRRO MANGA/BELO HORIZONTE VIA BR-040"]);
        Bus::create(["line" => "6572", "itinerary" => "JARDIM DAS OLIVEIRAS/BELO HORIZONTE "]);
        Bus::create(["line" => "6573", "itinerary" => "PARAGUAY/BELO HORIZONTE"]);
        Bus::create(["line" => "6577", "itinerary" => "ANDIROBA/BELO HORIZONTE"]);
        Bus::create(["line" => "6578", "itinerary" => "JARDIM DAS OLIVEIRAS VIA PARAGUAI/RIBEIRAO DAS NEVES "]);
        Bus::create(["line" => "6582", "itinerary" => "JARDIM DAS OLIVEIRAS/RIBEIRÃO DAS NEVES"]);
        Bus::create(["line" => "6583", "itinerary" => "TEJUCO/BELO HORIZONTE"]);
        Bus::create(["line" => "6587", "itinerary" => "IPE AMARELO VIA QUINTA SÃO JOSÉ/BELO HORIZONTE"]);
        Bus::create(["line" => "6588", "itinerary" => "ESMERALDAS/BELO HORIZONTE "]);
        Bus::create(["line" => "6600", "itinerary" => "IPE AMARELO/TERMINAL NOVA CONTAGEM"]);
        Bus::create(["line" => "6610", "itinerary" => "RECANTO VERDE VIA AGUA BRANCA/EST.ELDORADO S/ATEND.CID.IND."]);
        Bus::create(["line" => "6620", "itinerary" => "BAIRRO IPE AMARELO VIA VP1/BELO HORIZONTE"]);
        Bus::create(["line" => "6630", "itinerary" => "IPE AMARELO VIA BAIRRO LAGOA SECA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "6640", "itinerary" => "IPE AMARELO/ESTACAO ELDORADO VIA AGUA BRANCA/CID.INDUSTRIAL"]);
        Bus::create(["line" => "6650", "itinerary" => "RETIRO/TERMINAL NOVA CONTAGEM"]);
        Bus::create(["line" => "6660", "itinerary" => "TOPAZIO - NOVO RETIRO /BELO HORIZONTE"]);
        Bus::create(["line" => "6670", "itinerary" => "TOPAZIO-NOVO RETIRO/ESTACAO ELDORADO VIA CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "6680", "itinerary" => "NOVO RETIRO VIA AVENIDA B/TERMINAL NOVA CONTAGEM"]);
        Bus::create(["line" => "6690", "itinerary" => "NOVO RETIRO/TERMINAL NOVA CONTAGEM"]);
        Bus::create(["line" => "6700", "itinerary" => "ICAIVERA/ESTACAO ELDORADO VIA AVENIDA JOAO CESAR DE OLIVEIRA"]);
        Bus::create(["line" => "6710", "itinerary" => "ICAIVERA/ESTACAO ELDORADO VIA AGUA BRANCA"]);
        Bus::create(["line" => "6720", "itinerary" => "ICAIVERA/BELO HORIZONTE"]);
        Bus::create(["line" => "6721", "itinerary" => "ICAIVERA / BELO HORIZONTE VIA AV. SEMA"]);
        Bus::create(["line" => "6730", "itinerary" => "ICAIVERA VIA MORRO ALTO/ESTACAO ELDORADO "]);
        Bus::create(["line" => "6740", "itinerary" => "ICAIVERA VIA MORRO ALTO/ESTACAO ELDORADO  VIA CID.INDUSTRIAL"]);
        Bus::create(["line" => "6750", "itinerary" => "ICAIVERA/AGUA BRANCA V.CID.IND./EST.ELD."]);
        Bus::create(["line" => "6760", "itinerary" => "CIRCULAR BAIRRO TUPA/ICAIVERA/DARCI RIBEIRO/NOVA CONTAGEM"]);
        Bus::create(["line" => "6770", "itinerary" => "IPE AMARELO/EST.ELDORADO VIA  J.C.OLIVEIRA S/ATEND CID.IND."]);
        Bus::create(["line" => "6780", "itinerary" => "IPE AMARELO/BELO HORIZONTE  VIA VP2"]);
        Bus::create(["line" => "6790", "itinerary" => "RECANTO VERDE/EST.ELDORADO VIA AV.J.C.OLIVEIRA/C. INDUSTRIAL"]);
        Bus::create(["line" => "6810", "itinerary" => "DUMAVILLE/TROPEIROS/S. QUITERIA/CASTELO BRANCO/NOVA CONTAGEM"]);
        Bus::create(["line" => "6820", "itinerary" => "RECANTO VERDE/BELO HORIZONTE"]);
        Bus::create(["line" => "6981", "itinerary" => "CACHOEIRINHA/SÃO JOSÉ/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "6982", "itinerary" => "ESMERALDAS/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "6983", "itinerary" => "SANTA QUITERIA/ESMERALDAS/BELO HORIZONTE"]);
        Bus::create(["line" => "6984", "itinerary" => "URUCUIA/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "6986", "itinerary" => "BAIRRO DUMAVILLE/ESTAÇÃO ELDORADO VIA BAIRRO CIDADE JARDIM"]);
        Bus::create(["line" => "6987", "itinerary" => "DUMAVILLE/ESTAÇÃO ELDORADO "]);
        Bus::create(["line" => "6988", "itinerary" => "DUMAVILLE VIA SANTA QUITÉRIA/ESTAÇÃO ELDORADO "]);
        Bus::create(["line" => "6991", "itinerary" => "SANTO AFONSO/MARIMBÁ/ESTAÇÃO ELDORADO"]);
        Bus::create(["line" => "6992", "itinerary" => "BAMBUS / CAIO MARTINS / BELO HORIZONTE"]);
        Bus::create(["line" => "6993", "itinerary" => "ESMERALDAS/BETIM"]);
        Bus::create(["line" => "6994", "itinerary" => "BAMBÚS/CAIO MARTINS/STº AFONSO/MARIMBÁ/BETIM/EST. ELDORADO"]);
        Bus::create(["line" => "6995", "itinerary" => "ESMERALDAS/BETIM VIA DUMAVILLE"]);
        Bus::create(["line" => "6997", "itinerary" => "ESMERALDA VIA PRACA DO ROSARIO/BETIM"]);
        Bus::create(["line" => "7100", "itinerary" => "NOVO RIACHO VIA INCONFIDENTES/FLAVIO MARQUES LISBOA"]);
        Bus::create(["line" => "7110", "itinerary" => "RIACHO DAS PEDRAS A/BETANIA "]);
        Bus::create(["line" => "7120", "itinerary" => "RIACHO DAS PEDRAS VIA RUA RIO COMPRIDO/BETANIA "]);
        Bus::create(["line" => "7130", "itinerary" => "RIACHO/BELO HORIZONTE"]);
        Bus::create(["line" => "7140", "itinerary" => "RIACHO VIA AVENIDA FRANCISCO FIRMO DE MATOS/BELO HORIZONTE"]);
        Bus::create(["line" => "7150", "itinerary" => "NOVO RIACHO VIA INCONFIDENTES/BELO HORIZONTE"]);
        Bus::create(["line" => "7160", "itinerary" => "NOVO RIACHO VIA INCONFIDENTES VIA VULO/BELO HORIZONTE "]);
        Bus::create(["line" => "7170", "itinerary" => "PIEMONTE/BELO HORIZONTE"]);
        Bus::create(["line" => "7180", "itinerary" => "RIACHO 3 VIA INCONFIDENTES/BELO HORIZONTE"]);
        Bus::create(["line" => "7190", "itinerary" => "RIACHO-CONJUNTO LEMP/BELO HORIZONTE"]);
        Bus::create(["line" => "7400", "itinerary" => "INDUSTRIAL SAO LUIZ VIA CONJUNTO SAO CAETANO/BELO HORIZONTE"]);
        Bus::create(["line" => "7410", "itinerary" => "IMBIRUCU/BELO HORIZONTE"]);
        Bus::create(["line" => "7420", "itinerary" => "INDUSTRIAL VIA RUA ALECRIM/BELO HORIZONTE"]);
        Bus::create(["line" => "7430", "itinerary" => "VILA CRISTINA VIA LARANJEIRAS/BELO HORIZONTE"]);
        Bus::create(["line" => "7440", "itinerary" => "DUQUE DE CAXIAS/VILA CRISTINA VIA AV.AMAZONAS/BELO HORIZONTE"]);
        Bus::create(["line" => "7450", "itinerary" => "VILA CRISTINA VIA IMBIRUCU/ESTACAO ELDORADO"]);
        Bus::create(["line" => "7460", "itinerary" => "NOVA BADEN VIA LARANJEIRAS/ESTACAO ELDORADO"]);
        Bus::create(["line" => "7470", "itinerary" => "CONJUNTO SAO CAETANO/BELO HORIZONTE"]);
        Bus::create(["line" => "7480", "itinerary" => "BAIRRO JARDIM TERESOPOLIS/BELO HORIZONTE"]);
        Bus::create(["line" => "7490", "itinerary" => "SAO CAETANO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "7500", "itinerary" => "GRANJA VERDE VIA NOVA BADEN/ESTACAO ELDORADO "]);
        Bus::create(["line" => "7510", "itinerary" => "SAO CAETANO-JARDIM TERESOPOLIS/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "7520", "itinerary" => "GRANJA VERDE/ESTACAO ELDORADO"]);
        Bus::create(["line" => "7530", "itinerary" => "SAO CAETANO VIA NOVA BADEN/ESTACAO ELDORADO"]);
        Bus::create(["line" => "7531", "itinerary" => "NOVA BADEN / CIDADE INDUSTRIAL VIA SÃO CAETANO"]);
        Bus::create(["line" => "7540", "itinerary" => "ALVORADA VIA BR-381/BELO HORIZONTE"]);
        Bus::create(["line" => "7550", "itinerary" => "BAIRRO ALVORADA VIA VILA BOA ESPERANCA/BELO HORIZONTE"]);
        Bus::create(["line" => "7560", "itinerary" => "ALVORADA VIA BR-381/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "7570", "itinerary" => "BAIRRO ALVORADA VIA VILA BOA ESPERANCA/ESTACAO ELDORADO"]);
        Bus::create(["line" => "7580", "itinerary" => "MORADA DA SERRA/ESTACAO DIAMANTE"]);
        Bus::create(["line" => "7650", "itinerary" => "PETROLANDIA-SAO LUIZ VIA IMBIRUCU/BELO HORIZONTE"]);
        Bus::create(["line" => "7660", "itinerary" => "PETROLANDIA VIA RUA ILHEUS - VIA IMBIRUCU/BELO HORIZONTE"]);
        Bus::create(["line" => "7670", "itinerary" => "SAPUCAIAS/SAO LUIZ VIA BERNARDO MONTEIRO/BELO HORIZONTE"]);
        Bus::create(["line" => "7680", "itinerary" => "PETROLANDIA/BELO HORIZONTE VIA RUA 31"]);
        Bus::create(["line" => "7690", "itinerary" => "TROPICAL VIA AVENIDA A/BELO HORIZONTE"]);
        Bus::create(["line" => "7700", "itinerary" => "TROPICAL/BELO HORIZONTE"]);
        Bus::create(["line" => "7710", "itinerary" => "SAPUCAIA/BELO HORIZONTE"]);
        Bus::create(["line" => "7720", "itinerary" => "PETROLANDIA VIA FONTE GRANDE/BELO HORIZONTE"]);
        Bus::create(["line" => "7730", "itinerary" => "EXPRESSO CAPELINHA VIA JOAO CESAR OLIVEIRA/ESTACAO ELDORADO "]);
        Bus::create(["line" => "7740", "itinerary" => "IMBIRUCU/ESTACAO ELDORADO"]);
        Bus::create(["line" => "7750", "itinerary" => "IMBIRUCU VIA EXPRESSA/ESTACAO ELDORADO "]);
        Bus::create(["line" => "7760", "itinerary" => "CAPELINHA  VIA BERNARDO MONTEIRO/CIDADE INDUSTRIAL"]);
        Bus::create(["line" => "7770", "itinerary" => "CAPELINHA/CIDADE INDUSTRIAL "]);
        Bus::create(["line" => "7830", "itinerary" => "PARQUE FERNAO DIAS VIA MONTE CASTELO/BELO HORIZONTE"]);
        Bus::create(["line" => "7840", "itinerary" => "CONJUNTO BELA VISTA/BELO HORIZONTE"]);
        Bus::create(["line" => "7900", "itinerary" => "SANTA CRUZ/BELO HORIZONTE"]);
        Bus::create(["line" => "7905", "itinerary" => "SANTA CRUZ VIA VULO/BELO HORIZONTE"]);
        Bus::create(["line" => "7950", "itinerary" => "SANTA CRUZ/INDUSTRIAL NOVO"]);
        Bus::create(["line" => "7980", "itinerary" => "BOA VISTA/MAKRO"]);
        Bus::create(["line" => "8400", "itinerary" => "TERMINAL SÃO BENEDITO/TERMINAL JUSTINÓPOLIS"]);
    }
}